// Code generated by protoc-gen-micro. DO NOT EDIT.
// source: proto/example/example.proto

/*
Package go_micro_srv_User is a generated protocol buffer package.

It is generated from these files:
	proto/example/example.proto

It has these top-level messages:
	Message
	GetImageCptRequest
	GetImageCptResponse
	GetSmsCptRequest
	GetSmsCptResponse
	RegisterRequest
	RegisterResponse
	LoginRequest
	LoginResponse
	LogoutRequest
	LogoutResponse
	GetUserInfoRequest
	GetUserInfoResponse
	RenameRequest
	RenameResponse
	AuthRequest
	AuthResponse
	UploadAvatarRequest
	UploadAvatarResponse
*/
package go_micro_srv_User

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

import (
	context "context"
	client "github.com/micro/go-micro/client"
	server "github.com/micro/go-micro/server"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ client.Option
var _ server.Option

// Client API for Example service

type ExampleService interface {
	GetImageCpt(ctx context.Context, in *GetImageCptRequest, opts ...client.CallOption) (*GetImageCptResponse, error)
	GetSmsCpt(ctx context.Context, in *GetSmsCptRequest, opts ...client.CallOption) (*GetSmsCptResponse, error)
	Register(ctx context.Context, in *RegisterRequest, opts ...client.CallOption) (*RegisterResponse, error)
	Login(ctx context.Context, in *LoginRequest, opts ...client.CallOption) (*LoginResponse, error)
	Logout(ctx context.Context, in *LogoutRequest, opts ...client.CallOption) (*LogoutResponse, error)
	GetUserInfo(ctx context.Context, in *GetUserInfoRequest, opts ...client.CallOption) (*GetUserInfoResponse, error)
	Rename(ctx context.Context, in *RenameRequest, opts ...client.CallOption) (*RenameResponse, error)
	Auth(ctx context.Context, in *AuthRequest, opts ...client.CallOption) (*AuthResponse, error)
	UploadAvatar(ctx context.Context, in *UploadAvatarRequest, opts ...client.CallOption) (*UploadAvatarResponse, error)
}

type exampleService struct {
	c    client.Client
	name string
}

func NewExampleService(name string, c client.Client) ExampleService {
	if c == nil {
		c = client.NewClient()
	}
	if len(name) == 0 {
		name = "go.micro.srv.User"
	}
	return &exampleService{
		c:    c,
		name: name,
	}
}

func (c *exampleService) GetImageCpt(ctx context.Context, in *GetImageCptRequest, opts ...client.CallOption) (*GetImageCptResponse, error) {
	req := c.c.NewRequest(c.name, "Example.GetImageCpt", in)
	out := new(GetImageCptResponse)
	err := c.c.Call(ctx, req, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *exampleService) GetSmsCpt(ctx context.Context, in *GetSmsCptRequest, opts ...client.CallOption) (*GetSmsCptResponse, error) {
	req := c.c.NewRequest(c.name, "Example.GetSmsCpt", in)
	out := new(GetSmsCptResponse)
	err := c.c.Call(ctx, req, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *exampleService) Register(ctx context.Context, in *RegisterRequest, opts ...client.CallOption) (*RegisterResponse, error) {
	req := c.c.NewRequest(c.name, "Example.Register", in)
	out := new(RegisterResponse)
	err := c.c.Call(ctx, req, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *exampleService) Login(ctx context.Context, in *LoginRequest, opts ...client.CallOption) (*LoginResponse, error) {
	req := c.c.NewRequest(c.name, "Example.Login", in)
	out := new(LoginResponse)
	err := c.c.Call(ctx, req, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *exampleService) Logout(ctx context.Context, in *LogoutRequest, opts ...client.CallOption) (*LogoutResponse, error) {
	req := c.c.NewRequest(c.name, "Example.Logout", in)
	out := new(LogoutResponse)
	err := c.c.Call(ctx, req, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *exampleService) GetUserInfo(ctx context.Context, in *GetUserInfoRequest, opts ...client.CallOption) (*GetUserInfoResponse, error) {
	req := c.c.NewRequest(c.name, "Example.GetUserInfo", in)
	out := new(GetUserInfoResponse)
	err := c.c.Call(ctx, req, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *exampleService) Rename(ctx context.Context, in *RenameRequest, opts ...client.CallOption) (*RenameResponse, error) {
	req := c.c.NewRequest(c.name, "Example.Rename", in)
	out := new(RenameResponse)
	err := c.c.Call(ctx, req, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *exampleService) Auth(ctx context.Context, in *AuthRequest, opts ...client.CallOption) (*AuthResponse, error) {
	req := c.c.NewRequest(c.name, "Example.Auth", in)
	out := new(AuthResponse)
	err := c.c.Call(ctx, req, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *exampleService) UploadAvatar(ctx context.Context, in *UploadAvatarRequest, opts ...client.CallOption) (*UploadAvatarResponse, error) {
	req := c.c.NewRequest(c.name, "Example.UploadAvatar", in)
	out := new(UploadAvatarResponse)
	err := c.c.Call(ctx, req, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// Server API for Example service

type ExampleHandler interface {
	GetImageCpt(context.Context, *GetImageCptRequest, *GetImageCptResponse) error
	GetSmsCpt(context.Context, *GetSmsCptRequest, *GetSmsCptResponse) error
	Register(context.Context, *RegisterRequest, *RegisterResponse) error
	Login(context.Context, *LoginRequest, *LoginResponse) error
	Logout(context.Context, *LogoutRequest, *LogoutResponse) error
	GetUserInfo(context.Context, *GetUserInfoRequest, *GetUserInfoResponse) error
	Rename(context.Context, *RenameRequest, *RenameResponse) error
	Auth(context.Context, *AuthRequest, *AuthResponse) error
	UploadAvatar(context.Context, *UploadAvatarRequest, *UploadAvatarResponse) error
}

func RegisterExampleHandler(s server.Server, hdlr ExampleHandler, opts ...server.HandlerOption) error {
	type example interface {
		GetImageCpt(ctx context.Context, in *GetImageCptRequest, out *GetImageCptResponse) error
		GetSmsCpt(ctx context.Context, in *GetSmsCptRequest, out *GetSmsCptResponse) error
		Register(ctx context.Context, in *RegisterRequest, out *RegisterResponse) error
		Login(ctx context.Context, in *LoginRequest, out *LoginResponse) error
		Logout(ctx context.Context, in *LogoutRequest, out *LogoutResponse) error
		GetUserInfo(ctx context.Context, in *GetUserInfoRequest, out *GetUserInfoResponse) error
		Rename(ctx context.Context, in *RenameRequest, out *RenameResponse) error
		Auth(ctx context.Context, in *AuthRequest, out *AuthResponse) error
		UploadAvatar(ctx context.Context, in *UploadAvatarRequest, out *UploadAvatarResponse) error
	}
	type Example struct {
		example
	}
	h := &exampleHandler{hdlr}
	return s.Handle(s.NewHandler(&Example{h}, opts...))
}

type exampleHandler struct {
	ExampleHandler
}

func (h *exampleHandler) GetImageCpt(ctx context.Context, in *GetImageCptRequest, out *GetImageCptResponse) error {
	return h.ExampleHandler.GetImageCpt(ctx, in, out)
}

func (h *exampleHandler) GetSmsCpt(ctx context.Context, in *GetSmsCptRequest, out *GetSmsCptResponse) error {
	return h.ExampleHandler.GetSmsCpt(ctx, in, out)
}

func (h *exampleHandler) Register(ctx context.Context, in *RegisterRequest, out *RegisterResponse) error {
	return h.ExampleHandler.Register(ctx, in, out)
}

func (h *exampleHandler) Login(ctx context.Context, in *LoginRequest, out *LoginResponse) error {
	return h.ExampleHandler.Login(ctx, in, out)
}

func (h *exampleHandler) Logout(ctx context.Context, in *LogoutRequest, out *LogoutResponse) error {
	return h.ExampleHandler.Logout(ctx, in, out)
}

func (h *exampleHandler) GetUserInfo(ctx context.Context, in *GetUserInfoRequest, out *GetUserInfoResponse) error {
	return h.ExampleHandler.GetUserInfo(ctx, in, out)
}

func (h *exampleHandler) Rename(ctx context.Context, in *RenameRequest, out *RenameResponse) error {
	return h.ExampleHandler.Rename(ctx, in, out)
}

func (h *exampleHandler) Auth(ctx context.Context, in *AuthRequest, out *AuthResponse) error {
	return h.ExampleHandler.Auth(ctx, in, out)
}

func (h *exampleHandler) UploadAvatar(ctx context.Context, in *UploadAvatarRequest, out *UploadAvatarResponse) error {
	return h.ExampleHandler.UploadAvatar(ctx, in, out)
}
