// Code generated by protoc-gen-go. DO NOT EDIT.
// source: proto/example/example.proto

package go_micro_srv_User

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type Message struct {
	Say                  string   `protobuf:"bytes,1,opt,name=say,proto3" json:"say,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Message) Reset()         { *m = Message{} }
func (m *Message) String() string { return proto.CompactTextString(m) }
func (*Message) ProtoMessage()    {}
func (*Message) Descriptor() ([]byte, []int) {
	return fileDescriptor_097b3f5db5cf5789, []int{0}
}

func (m *Message) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Message.Unmarshal(m, b)
}
func (m *Message) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Message.Marshal(b, m, deterministic)
}
func (m *Message) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Message.Merge(m, src)
}
func (m *Message) XXX_Size() int {
	return xxx_messageInfo_Message.Size(m)
}
func (m *Message) XXX_DiscardUnknown() {
	xxx_messageInfo_Message.DiscardUnknown(m)
}

var xxx_messageInfo_Message proto.InternalMessageInfo

func (m *Message) GetSay() string {
	if m != nil {
		return m.Say
	}
	return ""
}

type GetCaptchaRequest struct {
	Uuid                 string   `protobuf:"bytes,1,opt,name=Uuid,proto3" json:"Uuid,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetCaptchaRequest) Reset()         { *m = GetCaptchaRequest{} }
func (m *GetCaptchaRequest) String() string { return proto.CompactTextString(m) }
func (*GetCaptchaRequest) ProtoMessage()    {}
func (*GetCaptchaRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_097b3f5db5cf5789, []int{1}
}

func (m *GetCaptchaRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetCaptchaRequest.Unmarshal(m, b)
}
func (m *GetCaptchaRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetCaptchaRequest.Marshal(b, m, deterministic)
}
func (m *GetCaptchaRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetCaptchaRequest.Merge(m, src)
}
func (m *GetCaptchaRequest) XXX_Size() int {
	return xxx_messageInfo_GetCaptchaRequest.Size(m)
}
func (m *GetCaptchaRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_GetCaptchaRequest.DiscardUnknown(m)
}

var xxx_messageInfo_GetCaptchaRequest proto.InternalMessageInfo

func (m *GetCaptchaRequest) GetUuid() string {
	if m != nil {
		return m.Uuid
	}
	return ""
}

type GetCaptchaResponse struct {
	ErrCode              string                    `protobuf:"bytes,1,opt,name=ErrCode,proto3" json:"ErrCode,omitempty"`
	ErrMsg               string                    `protobuf:"bytes,2,opt,name=ErrMsg,proto3" json:"ErrMsg,omitempty"`
	Pix                  []byte                    `protobuf:"bytes,3,opt,name=Pix,proto3" json:"Pix,omitempty"`
	Stride               int64                     `protobuf:"varint,4,opt,name=Stride,proto3" json:"Stride,omitempty"`
	Min                  *GetCaptchaResponse_Point `protobuf:"bytes,5,opt,name=Min,proto3" json:"Min,omitempty"`
	Max                  *GetCaptchaResponse_Point `protobuf:"bytes,6,opt,name=Max,proto3" json:"Max,omitempty"`
	XXX_NoUnkeyedLiteral struct{}                  `json:"-"`
	XXX_unrecognized     []byte                    `json:"-"`
	XXX_sizecache        int32                     `json:"-"`
}

func (m *GetCaptchaResponse) Reset()         { *m = GetCaptchaResponse{} }
func (m *GetCaptchaResponse) String() string { return proto.CompactTextString(m) }
func (*GetCaptchaResponse) ProtoMessage()    {}
func (*GetCaptchaResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_097b3f5db5cf5789, []int{2}
}

func (m *GetCaptchaResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetCaptchaResponse.Unmarshal(m, b)
}
func (m *GetCaptchaResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetCaptchaResponse.Marshal(b, m, deterministic)
}
func (m *GetCaptchaResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetCaptchaResponse.Merge(m, src)
}
func (m *GetCaptchaResponse) XXX_Size() int {
	return xxx_messageInfo_GetCaptchaResponse.Size(m)
}
func (m *GetCaptchaResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_GetCaptchaResponse.DiscardUnknown(m)
}

var xxx_messageInfo_GetCaptchaResponse proto.InternalMessageInfo

func (m *GetCaptchaResponse) GetErrCode() string {
	if m != nil {
		return m.ErrCode
	}
	return ""
}

func (m *GetCaptchaResponse) GetErrMsg() string {
	if m != nil {
		return m.ErrMsg
	}
	return ""
}

func (m *GetCaptchaResponse) GetPix() []byte {
	if m != nil {
		return m.Pix
	}
	return nil
}

func (m *GetCaptchaResponse) GetStride() int64 {
	if m != nil {
		return m.Stride
	}
	return 0
}

func (m *GetCaptchaResponse) GetMin() *GetCaptchaResponse_Point {
	if m != nil {
		return m.Min
	}
	return nil
}

func (m *GetCaptchaResponse) GetMax() *GetCaptchaResponse_Point {
	if m != nil {
		return m.Max
	}
	return nil
}

type GetCaptchaResponse_Point struct {
	X                    int64    `protobuf:"varint,1,opt,name=X,proto3" json:"X,omitempty"`
	Y                    int64    `protobuf:"varint,2,opt,name=Y,proto3" json:"Y,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetCaptchaResponse_Point) Reset()         { *m = GetCaptchaResponse_Point{} }
func (m *GetCaptchaResponse_Point) String() string { return proto.CompactTextString(m) }
func (*GetCaptchaResponse_Point) ProtoMessage()    {}
func (*GetCaptchaResponse_Point) Descriptor() ([]byte, []int) {
	return fileDescriptor_097b3f5db5cf5789, []int{2, 0}
}

func (m *GetCaptchaResponse_Point) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetCaptchaResponse_Point.Unmarshal(m, b)
}
func (m *GetCaptchaResponse_Point) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetCaptchaResponse_Point.Marshal(b, m, deterministic)
}
func (m *GetCaptchaResponse_Point) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetCaptchaResponse_Point.Merge(m, src)
}
func (m *GetCaptchaResponse_Point) XXX_Size() int {
	return xxx_messageInfo_GetCaptchaResponse_Point.Size(m)
}
func (m *GetCaptchaResponse_Point) XXX_DiscardUnknown() {
	xxx_messageInfo_GetCaptchaResponse_Point.DiscardUnknown(m)
}

var xxx_messageInfo_GetCaptchaResponse_Point proto.InternalMessageInfo

func (m *GetCaptchaResponse_Point) GetX() int64 {
	if m != nil {
		return m.X
	}
	return 0
}

func (m *GetCaptchaResponse_Point) GetY() int64 {
	if m != nil {
		return m.Y
	}
	return 0
}

type GetSmsCaptchaRequest struct {
	Uuid                 string   `protobuf:"bytes,1,opt,name=Uuid,proto3" json:"Uuid,omitempty"`
	Mobile               string   `protobuf:"bytes,2,opt,name=Mobile,proto3" json:"Mobile,omitempty"`
	Captcha              string   `protobuf:"bytes,3,opt,name=Captcha,proto3" json:"Captcha,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetSmsCaptchaRequest) Reset()         { *m = GetSmsCaptchaRequest{} }
func (m *GetSmsCaptchaRequest) String() string { return proto.CompactTextString(m) }
func (*GetSmsCaptchaRequest) ProtoMessage()    {}
func (*GetSmsCaptchaRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_097b3f5db5cf5789, []int{3}
}

func (m *GetSmsCaptchaRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetSmsCaptchaRequest.Unmarshal(m, b)
}
func (m *GetSmsCaptchaRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetSmsCaptchaRequest.Marshal(b, m, deterministic)
}
func (m *GetSmsCaptchaRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetSmsCaptchaRequest.Merge(m, src)
}
func (m *GetSmsCaptchaRequest) XXX_Size() int {
	return xxx_messageInfo_GetSmsCaptchaRequest.Size(m)
}
func (m *GetSmsCaptchaRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_GetSmsCaptchaRequest.DiscardUnknown(m)
}

var xxx_messageInfo_GetSmsCaptchaRequest proto.InternalMessageInfo

func (m *GetSmsCaptchaRequest) GetUuid() string {
	if m != nil {
		return m.Uuid
	}
	return ""
}

func (m *GetSmsCaptchaRequest) GetMobile() string {
	if m != nil {
		return m.Mobile
	}
	return ""
}

func (m *GetSmsCaptchaRequest) GetCaptcha() string {
	if m != nil {
		return m.Captcha
	}
	return ""
}

type GetSmsCaptchaResponse struct {
	ErrCode              string   `protobuf:"bytes,1,opt,name=ErrCode,proto3" json:"ErrCode,omitempty"`
	ErrMsg               string   `protobuf:"bytes,2,opt,name=ErrMsg,proto3" json:"ErrMsg,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetSmsCaptchaResponse) Reset()         { *m = GetSmsCaptchaResponse{} }
func (m *GetSmsCaptchaResponse) String() string { return proto.CompactTextString(m) }
func (*GetSmsCaptchaResponse) ProtoMessage()    {}
func (*GetSmsCaptchaResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_097b3f5db5cf5789, []int{4}
}

func (m *GetSmsCaptchaResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetSmsCaptchaResponse.Unmarshal(m, b)
}
func (m *GetSmsCaptchaResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetSmsCaptchaResponse.Marshal(b, m, deterministic)
}
func (m *GetSmsCaptchaResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetSmsCaptchaResponse.Merge(m, src)
}
func (m *GetSmsCaptchaResponse) XXX_Size() int {
	return xxx_messageInfo_GetSmsCaptchaResponse.Size(m)
}
func (m *GetSmsCaptchaResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_GetSmsCaptchaResponse.DiscardUnknown(m)
}

var xxx_messageInfo_GetSmsCaptchaResponse proto.InternalMessageInfo

func (m *GetSmsCaptchaResponse) GetErrCode() string {
	if m != nil {
		return m.ErrCode
	}
	return ""
}

func (m *GetSmsCaptchaResponse) GetErrMsg() string {
	if m != nil {
		return m.ErrMsg
	}
	return ""
}

type RegisterRequest struct {
	Mobile               string   `protobuf:"bytes,1,opt,name=Mobile,proto3" json:"Mobile,omitempty"`
	Password             string   `protobuf:"bytes,2,opt,name=Password,proto3" json:"Password,omitempty"`
	SmsCaptcha           string   `protobuf:"bytes,3,opt,name=SmsCaptcha,proto3" json:"SmsCaptcha,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *RegisterRequest) Reset()         { *m = RegisterRequest{} }
func (m *RegisterRequest) String() string { return proto.CompactTextString(m) }
func (*RegisterRequest) ProtoMessage()    {}
func (*RegisterRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_097b3f5db5cf5789, []int{5}
}

func (m *RegisterRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_RegisterRequest.Unmarshal(m, b)
}
func (m *RegisterRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_RegisterRequest.Marshal(b, m, deterministic)
}
func (m *RegisterRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_RegisterRequest.Merge(m, src)
}
func (m *RegisterRequest) XXX_Size() int {
	return xxx_messageInfo_RegisterRequest.Size(m)
}
func (m *RegisterRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_RegisterRequest.DiscardUnknown(m)
}

var xxx_messageInfo_RegisterRequest proto.InternalMessageInfo

func (m *RegisterRequest) GetMobile() string {
	if m != nil {
		return m.Mobile
	}
	return ""
}

func (m *RegisterRequest) GetPassword() string {
	if m != nil {
		return m.Password
	}
	return ""
}

func (m *RegisterRequest) GetSmsCaptcha() string {
	if m != nil {
		return m.SmsCaptcha
	}
	return ""
}

type RegisterResponse struct {
	ErrCode              string   `protobuf:"bytes,1,opt,name=ErrCode,proto3" json:"ErrCode,omitempty"`
	ErrMsg               string   `protobuf:"bytes,2,opt,name=ErrMsg,proto3" json:"ErrMsg,omitempty"`
	SessionId            string   `protobuf:"bytes,3,opt,name=SessionId,proto3" json:"SessionId,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *RegisterResponse) Reset()         { *m = RegisterResponse{} }
func (m *RegisterResponse) String() string { return proto.CompactTextString(m) }
func (*RegisterResponse) ProtoMessage()    {}
func (*RegisterResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_097b3f5db5cf5789, []int{6}
}

func (m *RegisterResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_RegisterResponse.Unmarshal(m, b)
}
func (m *RegisterResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_RegisterResponse.Marshal(b, m, deterministic)
}
func (m *RegisterResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_RegisterResponse.Merge(m, src)
}
func (m *RegisterResponse) XXX_Size() int {
	return xxx_messageInfo_RegisterResponse.Size(m)
}
func (m *RegisterResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_RegisterResponse.DiscardUnknown(m)
}

var xxx_messageInfo_RegisterResponse proto.InternalMessageInfo

func (m *RegisterResponse) GetErrCode() string {
	if m != nil {
		return m.ErrCode
	}
	return ""
}

func (m *RegisterResponse) GetErrMsg() string {
	if m != nil {
		return m.ErrMsg
	}
	return ""
}

func (m *RegisterResponse) GetSessionId() string {
	if m != nil {
		return m.SessionId
	}
	return ""
}

type LoginRequest struct {
	Mobile               string   `protobuf:"bytes,1,opt,name=Mobile,proto3" json:"Mobile,omitempty"`
	Password             string   `protobuf:"bytes,2,opt,name=Password,proto3" json:"Password,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *LoginRequest) Reset()         { *m = LoginRequest{} }
func (m *LoginRequest) String() string { return proto.CompactTextString(m) }
func (*LoginRequest) ProtoMessage()    {}
func (*LoginRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_097b3f5db5cf5789, []int{7}
}

func (m *LoginRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_LoginRequest.Unmarshal(m, b)
}
func (m *LoginRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_LoginRequest.Marshal(b, m, deterministic)
}
func (m *LoginRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_LoginRequest.Merge(m, src)
}
func (m *LoginRequest) XXX_Size() int {
	return xxx_messageInfo_LoginRequest.Size(m)
}
func (m *LoginRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_LoginRequest.DiscardUnknown(m)
}

var xxx_messageInfo_LoginRequest proto.InternalMessageInfo

func (m *LoginRequest) GetMobile() string {
	if m != nil {
		return m.Mobile
	}
	return ""
}

func (m *LoginRequest) GetPassword() string {
	if m != nil {
		return m.Password
	}
	return ""
}

type LoginResponse struct {
	ErrCode              string   `protobuf:"bytes,1,opt,name=ErrCode,proto3" json:"ErrCode,omitempty"`
	ErrMsg               string   `protobuf:"bytes,2,opt,name=ErrMsg,proto3" json:"ErrMsg,omitempty"`
	SessionId            string   `protobuf:"bytes,3,opt,name=SessionId,proto3" json:"SessionId,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *LoginResponse) Reset()         { *m = LoginResponse{} }
func (m *LoginResponse) String() string { return proto.CompactTextString(m) }
func (*LoginResponse) ProtoMessage()    {}
func (*LoginResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_097b3f5db5cf5789, []int{8}
}

func (m *LoginResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_LoginResponse.Unmarshal(m, b)
}
func (m *LoginResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_LoginResponse.Marshal(b, m, deterministic)
}
func (m *LoginResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_LoginResponse.Merge(m, src)
}
func (m *LoginResponse) XXX_Size() int {
	return xxx_messageInfo_LoginResponse.Size(m)
}
func (m *LoginResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_LoginResponse.DiscardUnknown(m)
}

var xxx_messageInfo_LoginResponse proto.InternalMessageInfo

func (m *LoginResponse) GetErrCode() string {
	if m != nil {
		return m.ErrCode
	}
	return ""
}

func (m *LoginResponse) GetErrMsg() string {
	if m != nil {
		return m.ErrMsg
	}
	return ""
}

func (m *LoginResponse) GetSessionId() string {
	if m != nil {
		return m.SessionId
	}
	return ""
}

type LogoutRequest struct {
	SessionId            string   `protobuf:"bytes,1,opt,name=SessionId,proto3" json:"SessionId,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *LogoutRequest) Reset()         { *m = LogoutRequest{} }
func (m *LogoutRequest) String() string { return proto.CompactTextString(m) }
func (*LogoutRequest) ProtoMessage()    {}
func (*LogoutRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_097b3f5db5cf5789, []int{9}
}

func (m *LogoutRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_LogoutRequest.Unmarshal(m, b)
}
func (m *LogoutRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_LogoutRequest.Marshal(b, m, deterministic)
}
func (m *LogoutRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_LogoutRequest.Merge(m, src)
}
func (m *LogoutRequest) XXX_Size() int {
	return xxx_messageInfo_LogoutRequest.Size(m)
}
func (m *LogoutRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_LogoutRequest.DiscardUnknown(m)
}

var xxx_messageInfo_LogoutRequest proto.InternalMessageInfo

func (m *LogoutRequest) GetSessionId() string {
	if m != nil {
		return m.SessionId
	}
	return ""
}

type LogoutResponse struct {
	ErrCode              string   `protobuf:"bytes,1,opt,name=ErrCode,proto3" json:"ErrCode,omitempty"`
	ErrMsg               string   `protobuf:"bytes,2,opt,name=ErrMsg,proto3" json:"ErrMsg,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *LogoutResponse) Reset()         { *m = LogoutResponse{} }
func (m *LogoutResponse) String() string { return proto.CompactTextString(m) }
func (*LogoutResponse) ProtoMessage()    {}
func (*LogoutResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_097b3f5db5cf5789, []int{10}
}

func (m *LogoutResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_LogoutResponse.Unmarshal(m, b)
}
func (m *LogoutResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_LogoutResponse.Marshal(b, m, deterministic)
}
func (m *LogoutResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_LogoutResponse.Merge(m, src)
}
func (m *LogoutResponse) XXX_Size() int {
	return xxx_messageInfo_LogoutResponse.Size(m)
}
func (m *LogoutResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_LogoutResponse.DiscardUnknown(m)
}

var xxx_messageInfo_LogoutResponse proto.InternalMessageInfo

func (m *LogoutResponse) GetErrCode() string {
	if m != nil {
		return m.ErrCode
	}
	return ""
}

func (m *LogoutResponse) GetErrMsg() string {
	if m != nil {
		return m.ErrMsg
	}
	return ""
}

type InfoRequest struct {
	SessionId            string   `protobuf:"bytes,1,opt,name=SessionId,proto3" json:"SessionId,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *InfoRequest) Reset()         { *m = InfoRequest{} }
func (m *InfoRequest) String() string { return proto.CompactTextString(m) }
func (*InfoRequest) ProtoMessage()    {}
func (*InfoRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_097b3f5db5cf5789, []int{11}
}

func (m *InfoRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_InfoRequest.Unmarshal(m, b)
}
func (m *InfoRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_InfoRequest.Marshal(b, m, deterministic)
}
func (m *InfoRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_InfoRequest.Merge(m, src)
}
func (m *InfoRequest) XXX_Size() int {
	return xxx_messageInfo_InfoRequest.Size(m)
}
func (m *InfoRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_InfoRequest.DiscardUnknown(m)
}

var xxx_messageInfo_InfoRequest proto.InternalMessageInfo

func (m *InfoRequest) GetSessionId() string {
	if m != nil {
		return m.SessionId
	}
	return ""
}

type InfoResponse struct {
	ErrCode              string   `protobuf:"bytes,1,opt,name=ErrCode,proto3" json:"ErrCode,omitempty"`
	ErrMsg               string   `protobuf:"bytes,2,opt,name=ErrMsg,proto3" json:"ErrMsg,omitempty"`
	Data                 []byte   `protobuf:"bytes,3,opt,name=Data,proto3" json:"Data,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *InfoResponse) Reset()         { *m = InfoResponse{} }
func (m *InfoResponse) String() string { return proto.CompactTextString(m) }
func (*InfoResponse) ProtoMessage()    {}
func (*InfoResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_097b3f5db5cf5789, []int{12}
}

func (m *InfoResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_InfoResponse.Unmarshal(m, b)
}
func (m *InfoResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_InfoResponse.Marshal(b, m, deterministic)
}
func (m *InfoResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_InfoResponse.Merge(m, src)
}
func (m *InfoResponse) XXX_Size() int {
	return xxx_messageInfo_InfoResponse.Size(m)
}
func (m *InfoResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_InfoResponse.DiscardUnknown(m)
}

var xxx_messageInfo_InfoResponse proto.InternalMessageInfo

func (m *InfoResponse) GetErrCode() string {
	if m != nil {
		return m.ErrCode
	}
	return ""
}

func (m *InfoResponse) GetErrMsg() string {
	if m != nil {
		return m.ErrMsg
	}
	return ""
}

func (m *InfoResponse) GetData() []byte {
	if m != nil {
		return m.Data
	}
	return nil
}

type AvatarRequest struct {
	SessionId            string   `protobuf:"bytes,1,opt,name=SessionId,proto3" json:"SessionId,omitempty"`
	Data                 []byte   `protobuf:"bytes,2,opt,name=Data,proto3" json:"Data,omitempty"`
	FileSize             int64    `protobuf:"varint,3,opt,name=FileSize,proto3" json:"FileSize,omitempty"`
	FileName             string   `protobuf:"bytes,4,opt,name=FileName,proto3" json:"FileName,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *AvatarRequest) Reset()         { *m = AvatarRequest{} }
func (m *AvatarRequest) String() string { return proto.CompactTextString(m) }
func (*AvatarRequest) ProtoMessage()    {}
func (*AvatarRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_097b3f5db5cf5789, []int{13}
}

func (m *AvatarRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_AvatarRequest.Unmarshal(m, b)
}
func (m *AvatarRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_AvatarRequest.Marshal(b, m, deterministic)
}
func (m *AvatarRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_AvatarRequest.Merge(m, src)
}
func (m *AvatarRequest) XXX_Size() int {
	return xxx_messageInfo_AvatarRequest.Size(m)
}
func (m *AvatarRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_AvatarRequest.DiscardUnknown(m)
}

var xxx_messageInfo_AvatarRequest proto.InternalMessageInfo

func (m *AvatarRequest) GetSessionId() string {
	if m != nil {
		return m.SessionId
	}
	return ""
}

func (m *AvatarRequest) GetData() []byte {
	if m != nil {
		return m.Data
	}
	return nil
}

func (m *AvatarRequest) GetFileSize() int64 {
	if m != nil {
		return m.FileSize
	}
	return 0
}

func (m *AvatarRequest) GetFileName() string {
	if m != nil {
		return m.FileName
	}
	return ""
}

type AvatarResponse struct {
	ErrCode              string   `protobuf:"bytes,1,opt,name=ErrCode,proto3" json:"ErrCode,omitempty"`
	ErrMsg               string   `protobuf:"bytes,2,opt,name=ErrMsg,proto3" json:"ErrMsg,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *AvatarResponse) Reset()         { *m = AvatarResponse{} }
func (m *AvatarResponse) String() string { return proto.CompactTextString(m) }
func (*AvatarResponse) ProtoMessage()    {}
func (*AvatarResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_097b3f5db5cf5789, []int{14}
}

func (m *AvatarResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_AvatarResponse.Unmarshal(m, b)
}
func (m *AvatarResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_AvatarResponse.Marshal(b, m, deterministic)
}
func (m *AvatarResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_AvatarResponse.Merge(m, src)
}
func (m *AvatarResponse) XXX_Size() int {
	return xxx_messageInfo_AvatarResponse.Size(m)
}
func (m *AvatarResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_AvatarResponse.DiscardUnknown(m)
}

var xxx_messageInfo_AvatarResponse proto.InternalMessageInfo

func (m *AvatarResponse) GetErrCode() string {
	if m != nil {
		return m.ErrCode
	}
	return ""
}

func (m *AvatarResponse) GetErrMsg() string {
	if m != nil {
		return m.ErrMsg
	}
	return ""
}

type UpdateUserNameRequest struct {
	SessionId            string   `protobuf:"bytes,1,opt,name=SessionId,proto3" json:"SessionId,omitempty"`
	UserName             string   `protobuf:"bytes,2,opt,name=UserName,proto3" json:"UserName,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *UpdateUserNameRequest) Reset()         { *m = UpdateUserNameRequest{} }
func (m *UpdateUserNameRequest) String() string { return proto.CompactTextString(m) }
func (*UpdateUserNameRequest) ProtoMessage()    {}
func (*UpdateUserNameRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_097b3f5db5cf5789, []int{15}
}

func (m *UpdateUserNameRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_UpdateUserNameRequest.Unmarshal(m, b)
}
func (m *UpdateUserNameRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_UpdateUserNameRequest.Marshal(b, m, deterministic)
}
func (m *UpdateUserNameRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_UpdateUserNameRequest.Merge(m, src)
}
func (m *UpdateUserNameRequest) XXX_Size() int {
	return xxx_messageInfo_UpdateUserNameRequest.Size(m)
}
func (m *UpdateUserNameRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_UpdateUserNameRequest.DiscardUnknown(m)
}

var xxx_messageInfo_UpdateUserNameRequest proto.InternalMessageInfo

func (m *UpdateUserNameRequest) GetSessionId() string {
	if m != nil {
		return m.SessionId
	}
	return ""
}

func (m *UpdateUserNameRequest) GetUserName() string {
	if m != nil {
		return m.UserName
	}
	return ""
}

type UpdateUserNameResponse struct {
	ErrCode              string   `protobuf:"bytes,1,opt,name=ErrCode,proto3" json:"ErrCode,omitempty"`
	ErrMsg               string   `protobuf:"bytes,2,opt,name=ErrMsg,proto3" json:"ErrMsg,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *UpdateUserNameResponse) Reset()         { *m = UpdateUserNameResponse{} }
func (m *UpdateUserNameResponse) String() string { return proto.CompactTextString(m) }
func (*UpdateUserNameResponse) ProtoMessage()    {}
func (*UpdateUserNameResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_097b3f5db5cf5789, []int{16}
}

func (m *UpdateUserNameResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_UpdateUserNameResponse.Unmarshal(m, b)
}
func (m *UpdateUserNameResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_UpdateUserNameResponse.Marshal(b, m, deterministic)
}
func (m *UpdateUserNameResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_UpdateUserNameResponse.Merge(m, src)
}
func (m *UpdateUserNameResponse) XXX_Size() int {
	return xxx_messageInfo_UpdateUserNameResponse.Size(m)
}
func (m *UpdateUserNameResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_UpdateUserNameResponse.DiscardUnknown(m)
}

var xxx_messageInfo_UpdateUserNameResponse proto.InternalMessageInfo

func (m *UpdateUserNameResponse) GetErrCode() string {
	if m != nil {
		return m.ErrCode
	}
	return ""
}

func (m *UpdateUserNameResponse) GetErrMsg() string {
	if m != nil {
		return m.ErrMsg
	}
	return ""
}

type AuthRequest struct {
	SessionId            string   `protobuf:"bytes,1,opt,name=SessionId,proto3" json:"SessionId,omitempty"`
	RealName             string   `protobuf:"bytes,2,opt,name=RealName,proto3" json:"RealName,omitempty"`
	IdCard               string   `protobuf:"bytes,3,opt,name=IdCard,proto3" json:"IdCard,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *AuthRequest) Reset()         { *m = AuthRequest{} }
func (m *AuthRequest) String() string { return proto.CompactTextString(m) }
func (*AuthRequest) ProtoMessage()    {}
func (*AuthRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_097b3f5db5cf5789, []int{17}
}

func (m *AuthRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_AuthRequest.Unmarshal(m, b)
}
func (m *AuthRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_AuthRequest.Marshal(b, m, deterministic)
}
func (m *AuthRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_AuthRequest.Merge(m, src)
}
func (m *AuthRequest) XXX_Size() int {
	return xxx_messageInfo_AuthRequest.Size(m)
}
func (m *AuthRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_AuthRequest.DiscardUnknown(m)
}

var xxx_messageInfo_AuthRequest proto.InternalMessageInfo

func (m *AuthRequest) GetSessionId() string {
	if m != nil {
		return m.SessionId
	}
	return ""
}

func (m *AuthRequest) GetRealName() string {
	if m != nil {
		return m.RealName
	}
	return ""
}

func (m *AuthRequest) GetIdCard() string {
	if m != nil {
		return m.IdCard
	}
	return ""
}

type AuthResponse struct {
	ErrCode              string   `protobuf:"bytes,1,opt,name=ErrCode,proto3" json:"ErrCode,omitempty"`
	ErrMsg               string   `protobuf:"bytes,2,opt,name=ErrMsg,proto3" json:"ErrMsg,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *AuthResponse) Reset()         { *m = AuthResponse{} }
func (m *AuthResponse) String() string { return proto.CompactTextString(m) }
func (*AuthResponse) ProtoMessage()    {}
func (*AuthResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_097b3f5db5cf5789, []int{18}
}

func (m *AuthResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_AuthResponse.Unmarshal(m, b)
}
func (m *AuthResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_AuthResponse.Marshal(b, m, deterministic)
}
func (m *AuthResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_AuthResponse.Merge(m, src)
}
func (m *AuthResponse) XXX_Size() int {
	return xxx_messageInfo_AuthResponse.Size(m)
}
func (m *AuthResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_AuthResponse.DiscardUnknown(m)
}

var xxx_messageInfo_AuthResponse proto.InternalMessageInfo

func (m *AuthResponse) GetErrCode() string {
	if m != nil {
		return m.ErrCode
	}
	return ""
}

func (m *AuthResponse) GetErrMsg() string {
	if m != nil {
		return m.ErrMsg
	}
	return ""
}

func init() {
	proto.RegisterType((*Message)(nil), "go.micro.srv.User.Message")
	proto.RegisterType((*GetCaptchaRequest)(nil), "go.micro.srv.User.GetCaptchaRequest")
	proto.RegisterType((*GetCaptchaResponse)(nil), "go.micro.srv.User.GetCaptchaResponse")
	proto.RegisterType((*GetCaptchaResponse_Point)(nil), "go.micro.srv.User.GetCaptchaResponse.Point")
	proto.RegisterType((*GetSmsCaptchaRequest)(nil), "go.micro.srv.User.GetSmsCaptchaRequest")
	proto.RegisterType((*GetSmsCaptchaResponse)(nil), "go.micro.srv.User.GetSmsCaptchaResponse")
	proto.RegisterType((*RegisterRequest)(nil), "go.micro.srv.User.RegisterRequest")
	proto.RegisterType((*RegisterResponse)(nil), "go.micro.srv.User.RegisterResponse")
	proto.RegisterType((*LoginRequest)(nil), "go.micro.srv.User.LoginRequest")
	proto.RegisterType((*LoginResponse)(nil), "go.micro.srv.User.LoginResponse")
	proto.RegisterType((*LogoutRequest)(nil), "go.micro.srv.User.LogoutRequest")
	proto.RegisterType((*LogoutResponse)(nil), "go.micro.srv.User.LogoutResponse")
	proto.RegisterType((*InfoRequest)(nil), "go.micro.srv.User.InfoRequest")
	proto.RegisterType((*InfoResponse)(nil), "go.micro.srv.User.InfoResponse")
	proto.RegisterType((*AvatarRequest)(nil), "go.micro.srv.User.AvatarRequest")
	proto.RegisterType((*AvatarResponse)(nil), "go.micro.srv.User.AvatarResponse")
	proto.RegisterType((*UpdateUserNameRequest)(nil), "go.micro.srv.User.UpdateUserNameRequest")
	proto.RegisterType((*UpdateUserNameResponse)(nil), "go.micro.srv.User.UpdateUserNameResponse")
	proto.RegisterType((*AuthRequest)(nil), "go.micro.srv.User.AuthRequest")
	proto.RegisterType((*AuthResponse)(nil), "go.micro.srv.User.AuthResponse")
}

func init() { proto.RegisterFile("proto/example/example.proto", fileDescriptor_097b3f5db5cf5789) }

var fileDescriptor_097b3f5db5cf5789 = []byte{
	// 694 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xb4, 0x56, 0x71, 0x4f, 0xdb, 0x3e,
	0x10, 0x25, 0xa4, 0x14, 0x7a, 0x14, 0x7e, 0x60, 0xfd, 0x40, 0x51, 0x98, 0xa0, 0x33, 0x9b, 0xe8,
	0x84, 0x96, 0x49, 0xec, 0xef, 0x49, 0x63, 0x8c, 0xa1, 0x4e, 0x74, 0x63, 0xe9, 0x2a, 0x81, 0x36,
	0x09, 0x19, 0xe2, 0x95, 0x48, 0x6d, 0xdd, 0xd9, 0x2e, 0x2b, 0xfb, 0x18, 0xdb, 0x17, 0x9e, 0xec,
	0xc4, 0x49, 0x4a, 0x03, 0x54, 0x99, 0xf6, 0x17, 0x7e, 0xc9, 0xbb, 0xbb, 0x77, 0x17, 0xdf, 0xa3,
	0xb0, 0x31, 0xe0, 0x4c, 0xb2, 0x17, 0x74, 0x44, 0x7a, 0x83, 0x2e, 0x35, 0x7f, 0x3d, 0xfd, 0x14,
	0xad, 0x76, 0x98, 0xd7, 0x0b, 0x2f, 0x39, 0xf3, 0x04, 0xbf, 0xf6, 0xda, 0x82, 0x72, 0xbc, 0x01,
	0xf3, 0x4d, 0x2a, 0x04, 0xe9, 0x50, 0xb4, 0x02, 0xb6, 0x20, 0x37, 0x8e, 0x55, 0xb3, 0xea, 0x15,
	0x5f, 0x1d, 0xf1, 0x0e, 0xac, 0x1e, 0x51, 0x79, 0x40, 0x06, 0xf2, 0xf2, 0x8a, 0xf8, 0xf4, 0xfb,
	0x90, 0x0a, 0x89, 0x10, 0x94, 0xda, 0xc3, 0x30, 0x88, 0x79, 0xfa, 0x8c, 0x7f, 0xcf, 0x02, 0xca,
	0x32, 0xc5, 0x80, 0xf5, 0x05, 0x45, 0x0e, 0xcc, 0x1f, 0x72, 0x7e, 0xc0, 0x02, 0x1a, 0xb3, 0x0d,
	0x44, 0xeb, 0x50, 0x3e, 0xe4, 0xbc, 0x29, 0x3a, 0xce, 0xac, 0x7e, 0x11, 0x23, 0xa5, 0xe1, 0x24,
	0x1c, 0x39, 0x76, 0xcd, 0xaa, 0x57, 0x7d, 0x75, 0x54, 0xcc, 0x96, 0xe4, 0x61, 0x40, 0x9d, 0x52,
	0xcd, 0xaa, 0xdb, 0x7e, 0x8c, 0xd0, 0x2b, 0xb0, 0x9b, 0x61, 0xdf, 0x99, 0xab, 0x59, 0xf5, 0xc5,
	0xbd, 0x5d, 0x6f, 0xa2, 0x33, 0x6f, 0x52, 0x8f, 0x77, 0xc2, 0xc2, 0xbe, 0xf4, 0x55, 0x9c, 0x0e,
	0x27, 0x23, 0xa7, 0x5c, 0x24, 0x9c, 0x8c, 0xdc, 0x6d, 0x98, 0xd3, 0x08, 0x55, 0xc1, 0x3a, 0xd5,
	0xcd, 0xd9, 0xbe, 0x75, 0xaa, 0xd0, 0x99, 0xee, 0xc8, 0xf6, 0xad, 0x33, 0xfc, 0x15, 0xfe, 0x3f,
	0xa2, 0xb2, 0xd5, 0x13, 0x0f, 0x4f, 0x50, 0xb5, 0xd9, 0x64, 0x17, 0x61, 0x97, 0x9a, 0x81, 0x44,
	0x48, 0x8d, 0x30, 0x8e, 0xd6, 0x43, 0xa9, 0xf8, 0x06, 0xe2, 0x06, 0xac, 0xdd, 0xca, 0x5e, 0x74,
	0xea, 0x98, 0xc2, 0x7f, 0x3e, 0xed, 0x84, 0x42, 0x52, 0x6e, 0x34, 0xa6, 0x7a, 0xac, 0x31, 0x3d,
	0x2e, 0x2c, 0x9c, 0x10, 0x21, 0x7e, 0x30, 0x1e, 0xc4, 0x49, 0x12, 0x8c, 0x36, 0x01, 0x52, 0x39,
	0xb1, 0xdc, 0xcc, 0x13, 0x7c, 0x01, 0x2b, 0x69, 0x99, 0xc2, 0x57, 0xe4, 0x11, 0x54, 0x5a, 0x54,
	0x88, 0x90, 0xf5, 0x1b, 0x41, 0x5c, 0x24, 0x7d, 0x80, 0xdf, 0x40, 0xf5, 0x98, 0x75, 0xc2, 0xfe,
	0x5f, 0xf4, 0x81, 0xcf, 0x61, 0x29, 0xce, 0xf1, 0x8f, 0x44, 0x3e, 0xd7, 0x05, 0xd8, 0x50, 0x1a,
	0x95, 0x63, 0x74, 0x6b, 0xb2, 0xa7, 0x65, 0x43, 0x2f, 0xfc, 0x89, 0x77, 0x61, 0xb1, 0xd1, 0xff,
	0xc6, 0xa6, 0x2b, 0xf8, 0x19, 0xaa, 0x11, 0xb9, 0x70, 0xff, 0x08, 0x4a, 0x6f, 0x89, 0x24, 0xf1,
	0x22, 0xeb, 0x33, 0xbe, 0x81, 0xa5, 0xfd, 0x6b, 0x22, 0x09, 0x9f, 0x4a, 0x44, 0x92, 0x62, 0x36,
	0x4d, 0xa1, 0xbe, 0xda, 0xbb, 0xb0, 0x4b, 0x5b, 0xe1, 0x4f, 0xaa, 0x53, 0xdb, 0x7e, 0x82, 0xcd,
	0xbb, 0x0f, 0xa4, 0x17, 0x59, 0x45, 0xc5, 0x4f, 0xb0, 0x9a, 0xa0, 0x29, 0x5d, 0x78, 0x82, 0x9f,
	0x60, 0xad, 0x3d, 0x08, 0x88, 0xa4, 0xca, 0x1e, 0x54, 0xd6, 0xe9, 0xda, 0x70, 0x61, 0xc1, 0x04,
	0x98, 0x8b, 0x66, 0x30, 0x7e, 0x0f, 0xeb, 0xb7, 0x53, 0x16, 0x96, 0x77, 0x0e, 0x8b, 0xfb, 0x43,
	0x79, 0x35, 0xb5, 0x28, 0x9f, 0x92, 0x6e, 0x56, 0x94, 0xc1, 0xaa, 0x40, 0x23, 0x38, 0x20, 0xdc,
	0xdc, 0xdb, 0x18, 0xe1, 0xd7, 0x50, 0x8d, 0x0a, 0x14, 0x95, 0xb8, 0xf7, 0xab, 0x0c, 0xf3, 0x87,
	0xd1, 0x3f, 0x24, 0xf4, 0x05, 0x20, 0x75, 0x58, 0xf4, 0xe4, 0x01, 0x03, 0xd6, 0x3d, 0xb9, 0x4f,
	0xa7, 0xb2, 0x69, 0x3c, 0x83, 0x02, 0x58, 0x1a, 0xb3, 0x46, 0xb4, 0x93, 0x1f, 0x39, 0x61, 0xcd,
	0x6e, 0xfd, 0x61, 0x62, 0x52, 0xa5, 0xad, 0x86, 0x18, 0xd9, 0x19, 0xc2, 0x39, 0x71, 0xb7, 0x2c,
	0xd5, 0xdd, 0xbe, 0x97, 0x93, 0xa4, 0x3d, 0x86, 0x39, 0xed, 0x3e, 0x68, 0x2b, 0x87, 0x9f, 0xf5,
	0x36, 0xb7, 0x76, 0x37, 0x21, 0xc9, 0xf6, 0x11, 0xca, 0x91, 0x77, 0xa0, 0x3b, 0xd8, 0xa9, 0x0b,
	0xb9, 0x8f, 0xef, 0x61, 0x24, 0x09, 0x1b, 0x50, 0x52, 0xde, 0x80, 0x36, 0x73, 0xc8, 0x19, 0x87,
	0x71, 0xb7, 0xee, 0x7c, 0x9f, 0xd5, 0x16, 0x6d, 0x65, 0xae, 0xb6, 0x31, 0xaf, 0xc8, 0xd5, 0x36,
	0xbe, 0xd2, 0x78, 0x06, 0x75, 0x60, 0x79, 0x7c, 0x9f, 0x50, 0xde, 0xf7, 0xcc, 0xdd, 0x62, 0xf7,
	0xd9, 0x14, 0xcc, 0xec, 0x10, 0xd4, 0x2e, 0xe4, 0x0e, 0x21, 0xb3, 0x85, 0xb9, 0x43, 0xc8, 0x2e,
	0x11, 0x9e, 0xb9, 0x28, 0xeb, 0x9f, 0x66, 0x2f, 0xff, 0x04, 0x00, 0x00, 0xff, 0xff, 0x77, 0x0e,
	0x91, 0xdd, 0xb9, 0x09, 0x00, 0x00,
}
