// Code generated by protoc-gen-go. DO NOT EDIT.
// source: proto/example/example.proto

package go_micro_srv_user

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type Message struct {
	Say                  string   `protobuf:"bytes,1,opt,name=say,proto3" json:"say,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Message) Reset()         { *m = Message{} }
func (m *Message) String() string { return proto.CompactTextString(m) }
func (*Message) ProtoMessage()    {}
func (*Message) Descriptor() ([]byte, []int) {
	return fileDescriptor_097b3f5db5cf5789, []int{0}
}

func (m *Message) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Message.Unmarshal(m, b)
}
func (m *Message) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Message.Marshal(b, m, deterministic)
}
func (m *Message) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Message.Merge(m, src)
}
func (m *Message) XXX_Size() int {
	return xxx_messageInfo_Message.Size(m)
}
func (m *Message) XXX_DiscardUnknown() {
	xxx_messageInfo_Message.DiscardUnknown(m)
}

var xxx_messageInfo_Message proto.InternalMessageInfo

func (m *Message) GetSay() string {
	if m != nil {
		return m.Say
	}
	return ""
}

type GenerateIdRequest struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GenerateIdRequest) Reset()         { *m = GenerateIdRequest{} }
func (m *GenerateIdRequest) String() string { return proto.CompactTextString(m) }
func (*GenerateIdRequest) ProtoMessage()    {}
func (*GenerateIdRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_097b3f5db5cf5789, []int{1}
}

func (m *GenerateIdRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GenerateIdRequest.Unmarshal(m, b)
}
func (m *GenerateIdRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GenerateIdRequest.Marshal(b, m, deterministic)
}
func (m *GenerateIdRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GenerateIdRequest.Merge(m, src)
}
func (m *GenerateIdRequest) XXX_Size() int {
	return xxx_messageInfo_GenerateIdRequest.Size(m)
}
func (m *GenerateIdRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_GenerateIdRequest.DiscardUnknown(m)
}

var xxx_messageInfo_GenerateIdRequest proto.InternalMessageInfo

type GenerateIdResponse struct {
	UserId               string   `protobuf:"bytes,1,opt,name=UserId,proto3" json:"UserId,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GenerateIdResponse) Reset()         { *m = GenerateIdResponse{} }
func (m *GenerateIdResponse) String() string { return proto.CompactTextString(m) }
func (*GenerateIdResponse) ProtoMessage()    {}
func (*GenerateIdResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_097b3f5db5cf5789, []int{2}
}

func (m *GenerateIdResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GenerateIdResponse.Unmarshal(m, b)
}
func (m *GenerateIdResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GenerateIdResponse.Marshal(b, m, deterministic)
}
func (m *GenerateIdResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GenerateIdResponse.Merge(m, src)
}
func (m *GenerateIdResponse) XXX_Size() int {
	return xxx_messageInfo_GenerateIdResponse.Size(m)
}
func (m *GenerateIdResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_GenerateIdResponse.DiscardUnknown(m)
}

var xxx_messageInfo_GenerateIdResponse proto.InternalMessageInfo

func (m *GenerateIdResponse) GetUserId() string {
	if m != nil {
		return m.UserId
	}
	return ""
}

type CaptchaRequest struct {
	UserId               string   `protobuf:"bytes,1,opt,name=UserId,proto3" json:"UserId,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *CaptchaRequest) Reset()         { *m = CaptchaRequest{} }
func (m *CaptchaRequest) String() string { return proto.CompactTextString(m) }
func (*CaptchaRequest) ProtoMessage()    {}
func (*CaptchaRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_097b3f5db5cf5789, []int{3}
}

func (m *CaptchaRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CaptchaRequest.Unmarshal(m, b)
}
func (m *CaptchaRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CaptchaRequest.Marshal(b, m, deterministic)
}
func (m *CaptchaRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CaptchaRequest.Merge(m, src)
}
func (m *CaptchaRequest) XXX_Size() int {
	return xxx_messageInfo_CaptchaRequest.Size(m)
}
func (m *CaptchaRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_CaptchaRequest.DiscardUnknown(m)
}

var xxx_messageInfo_CaptchaRequest proto.InternalMessageInfo

func (m *CaptchaRequest) GetUserId() string {
	if m != nil {
		return m.UserId
	}
	return ""
}

type CaptchaResponse struct {
	Pix                  []byte                 `protobuf:"bytes,1,opt,name=Pix,proto3" json:"Pix,omitempty"`
	Stride               int64                  `protobuf:"varint,2,opt,name=Stride,proto3" json:"Stride,omitempty"`
	Min                  *CaptchaResponse_Point `protobuf:"bytes,3,opt,name=Min,proto3" json:"Min,omitempty"`
	Max                  *CaptchaResponse_Point `protobuf:"bytes,4,opt,name=Max,proto3" json:"Max,omitempty"`
	XXX_NoUnkeyedLiteral struct{}               `json:"-"`
	XXX_unrecognized     []byte                 `json:"-"`
	XXX_sizecache        int32                  `json:"-"`
}

func (m *CaptchaResponse) Reset()         { *m = CaptchaResponse{} }
func (m *CaptchaResponse) String() string { return proto.CompactTextString(m) }
func (*CaptchaResponse) ProtoMessage()    {}
func (*CaptchaResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_097b3f5db5cf5789, []int{4}
}

func (m *CaptchaResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CaptchaResponse.Unmarshal(m, b)
}
func (m *CaptchaResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CaptchaResponse.Marshal(b, m, deterministic)
}
func (m *CaptchaResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CaptchaResponse.Merge(m, src)
}
func (m *CaptchaResponse) XXX_Size() int {
	return xxx_messageInfo_CaptchaResponse.Size(m)
}
func (m *CaptchaResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_CaptchaResponse.DiscardUnknown(m)
}

var xxx_messageInfo_CaptchaResponse proto.InternalMessageInfo

func (m *CaptchaResponse) GetPix() []byte {
	if m != nil {
		return m.Pix
	}
	return nil
}

func (m *CaptchaResponse) GetStride() int64 {
	if m != nil {
		return m.Stride
	}
	return 0
}

func (m *CaptchaResponse) GetMin() *CaptchaResponse_Point {
	if m != nil {
		return m.Min
	}
	return nil
}

func (m *CaptchaResponse) GetMax() *CaptchaResponse_Point {
	if m != nil {
		return m.Max
	}
	return nil
}

type CaptchaResponse_Point struct {
	X                    int64    `protobuf:"varint,1,opt,name=X,proto3" json:"X,omitempty"`
	Y                    int64    `protobuf:"varint,2,opt,name=Y,proto3" json:"Y,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *CaptchaResponse_Point) Reset()         { *m = CaptchaResponse_Point{} }
func (m *CaptchaResponse_Point) String() string { return proto.CompactTextString(m) }
func (*CaptchaResponse_Point) ProtoMessage()    {}
func (*CaptchaResponse_Point) Descriptor() ([]byte, []int) {
	return fileDescriptor_097b3f5db5cf5789, []int{4, 0}
}

func (m *CaptchaResponse_Point) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CaptchaResponse_Point.Unmarshal(m, b)
}
func (m *CaptchaResponse_Point) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CaptchaResponse_Point.Marshal(b, m, deterministic)
}
func (m *CaptchaResponse_Point) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CaptchaResponse_Point.Merge(m, src)
}
func (m *CaptchaResponse_Point) XXX_Size() int {
	return xxx_messageInfo_CaptchaResponse_Point.Size(m)
}
func (m *CaptchaResponse_Point) XXX_DiscardUnknown() {
	xxx_messageInfo_CaptchaResponse_Point.DiscardUnknown(m)
}

var xxx_messageInfo_CaptchaResponse_Point proto.InternalMessageInfo

func (m *CaptchaResponse_Point) GetX() int64 {
	if m != nil {
		return m.X
	}
	return 0
}

func (m *CaptchaResponse_Point) GetY() int64 {
	if m != nil {
		return m.Y
	}
	return 0
}

type SmsCaptchaRequest struct {
	UserId               string   `protobuf:"bytes,1,opt,name=UserId,proto3" json:"UserId,omitempty"`
	Mobile               string   `protobuf:"bytes,2,opt,name=Mobile,proto3" json:"Mobile,omitempty"`
	Captcha              string   `protobuf:"bytes,3,opt,name=Captcha,proto3" json:"Captcha,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *SmsCaptchaRequest) Reset()         { *m = SmsCaptchaRequest{} }
func (m *SmsCaptchaRequest) String() string { return proto.CompactTextString(m) }
func (*SmsCaptchaRequest) ProtoMessage()    {}
func (*SmsCaptchaRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_097b3f5db5cf5789, []int{5}
}

func (m *SmsCaptchaRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SmsCaptchaRequest.Unmarshal(m, b)
}
func (m *SmsCaptchaRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SmsCaptchaRequest.Marshal(b, m, deterministic)
}
func (m *SmsCaptchaRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SmsCaptchaRequest.Merge(m, src)
}
func (m *SmsCaptchaRequest) XXX_Size() int {
	return xxx_messageInfo_SmsCaptchaRequest.Size(m)
}
func (m *SmsCaptchaRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_SmsCaptchaRequest.DiscardUnknown(m)
}

var xxx_messageInfo_SmsCaptchaRequest proto.InternalMessageInfo

func (m *SmsCaptchaRequest) GetUserId() string {
	if m != nil {
		return m.UserId
	}
	return ""
}

func (m *SmsCaptchaRequest) GetMobile() string {
	if m != nil {
		return m.Mobile
	}
	return ""
}

func (m *SmsCaptchaRequest) GetCaptcha() string {
	if m != nil {
		return m.Captcha
	}
	return ""
}

type SmsCaptchaResponse struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *SmsCaptchaResponse) Reset()         { *m = SmsCaptchaResponse{} }
func (m *SmsCaptchaResponse) String() string { return proto.CompactTextString(m) }
func (*SmsCaptchaResponse) ProtoMessage()    {}
func (*SmsCaptchaResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_097b3f5db5cf5789, []int{6}
}

func (m *SmsCaptchaResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SmsCaptchaResponse.Unmarshal(m, b)
}
func (m *SmsCaptchaResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SmsCaptchaResponse.Marshal(b, m, deterministic)
}
func (m *SmsCaptchaResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SmsCaptchaResponse.Merge(m, src)
}
func (m *SmsCaptchaResponse) XXX_Size() int {
	return xxx_messageInfo_SmsCaptchaResponse.Size(m)
}
func (m *SmsCaptchaResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_SmsCaptchaResponse.DiscardUnknown(m)
}

var xxx_messageInfo_SmsCaptchaResponse proto.InternalMessageInfo

type RegisterRequest struct {
	UserId               string   `protobuf:"bytes,1,opt,name=UserId,proto3" json:"UserId,omitempty"`
	Mobile               string   `protobuf:"bytes,2,opt,name=Mobile,proto3" json:"Mobile,omitempty"`
	SmsCaptcha           string   `protobuf:"bytes,3,opt,name=SmsCaptcha,proto3" json:"SmsCaptcha,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *RegisterRequest) Reset()         { *m = RegisterRequest{} }
func (m *RegisterRequest) String() string { return proto.CompactTextString(m) }
func (*RegisterRequest) ProtoMessage()    {}
func (*RegisterRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_097b3f5db5cf5789, []int{7}
}

func (m *RegisterRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_RegisterRequest.Unmarshal(m, b)
}
func (m *RegisterRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_RegisterRequest.Marshal(b, m, deterministic)
}
func (m *RegisterRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_RegisterRequest.Merge(m, src)
}
func (m *RegisterRequest) XXX_Size() int {
	return xxx_messageInfo_RegisterRequest.Size(m)
}
func (m *RegisterRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_RegisterRequest.DiscardUnknown(m)
}

var xxx_messageInfo_RegisterRequest proto.InternalMessageInfo

func (m *RegisterRequest) GetUserId() string {
	if m != nil {
		return m.UserId
	}
	return ""
}

func (m *RegisterRequest) GetMobile() string {
	if m != nil {
		return m.Mobile
	}
	return ""
}

func (m *RegisterRequest) GetSmsCaptcha() string {
	if m != nil {
		return m.SmsCaptcha
	}
	return ""
}

type RegisterResponse struct {
	UserId               string   `protobuf:"bytes,1,opt,name=UserId,proto3" json:"UserId,omitempty"`
	Mobile               string   `protobuf:"bytes,2,opt,name=Mobile,proto3" json:"Mobile,omitempty"`
	PublicKey            string   `protobuf:"bytes,3,opt,name=PublicKey,proto3" json:"PublicKey,omitempty"`
	PrivateKey           string   `protobuf:"bytes,4,opt,name=PrivateKey,proto3" json:"PrivateKey,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *RegisterResponse) Reset()         { *m = RegisterResponse{} }
func (m *RegisterResponse) String() string { return proto.CompactTextString(m) }
func (*RegisterResponse) ProtoMessage()    {}
func (*RegisterResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_097b3f5db5cf5789, []int{8}
}

func (m *RegisterResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_RegisterResponse.Unmarshal(m, b)
}
func (m *RegisterResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_RegisterResponse.Marshal(b, m, deterministic)
}
func (m *RegisterResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_RegisterResponse.Merge(m, src)
}
func (m *RegisterResponse) XXX_Size() int {
	return xxx_messageInfo_RegisterResponse.Size(m)
}
func (m *RegisterResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_RegisterResponse.DiscardUnknown(m)
}

var xxx_messageInfo_RegisterResponse proto.InternalMessageInfo

func (m *RegisterResponse) GetUserId() string {
	if m != nil {
		return m.UserId
	}
	return ""
}

func (m *RegisterResponse) GetMobile() string {
	if m != nil {
		return m.Mobile
	}
	return ""
}

func (m *RegisterResponse) GetPublicKey() string {
	if m != nil {
		return m.PublicKey
	}
	return ""
}

func (m *RegisterResponse) GetPrivateKey() string {
	if m != nil {
		return m.PrivateKey
	}
	return ""
}

type GetInfoRequest struct {
	Mobile               string   `protobuf:"bytes,1,opt,name=Mobile,proto3" json:"Mobile,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetInfoRequest) Reset()         { *m = GetInfoRequest{} }
func (m *GetInfoRequest) String() string { return proto.CompactTextString(m) }
func (*GetInfoRequest) ProtoMessage()    {}
func (*GetInfoRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_097b3f5db5cf5789, []int{9}
}

func (m *GetInfoRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetInfoRequest.Unmarshal(m, b)
}
func (m *GetInfoRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetInfoRequest.Marshal(b, m, deterministic)
}
func (m *GetInfoRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetInfoRequest.Merge(m, src)
}
func (m *GetInfoRequest) XXX_Size() int {
	return xxx_messageInfo_GetInfoRequest.Size(m)
}
func (m *GetInfoRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_GetInfoRequest.DiscardUnknown(m)
}

var xxx_messageInfo_GetInfoRequest proto.InternalMessageInfo

func (m *GetInfoRequest) GetMobile() string {
	if m != nil {
		return m.Mobile
	}
	return ""
}

type GetInfoResponse struct {
	Data                 []byte   `protobuf:"bytes,1,opt,name=Data,proto3" json:"Data,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetInfoResponse) Reset()         { *m = GetInfoResponse{} }
func (m *GetInfoResponse) String() string { return proto.CompactTextString(m) }
func (*GetInfoResponse) ProtoMessage()    {}
func (*GetInfoResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_097b3f5db5cf5789, []int{10}
}

func (m *GetInfoResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetInfoResponse.Unmarshal(m, b)
}
func (m *GetInfoResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetInfoResponse.Marshal(b, m, deterministic)
}
func (m *GetInfoResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetInfoResponse.Merge(m, src)
}
func (m *GetInfoResponse) XXX_Size() int {
	return xxx_messageInfo_GetInfoResponse.Size(m)
}
func (m *GetInfoResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_GetInfoResponse.DiscardUnknown(m)
}

var xxx_messageInfo_GetInfoResponse proto.InternalMessageInfo

func (m *GetInfoResponse) GetData() []byte {
	if m != nil {
		return m.Data
	}
	return nil
}

type AvatarRequest struct {
	Mobile               string   `protobuf:"bytes,1,opt,name=Mobile,proto3" json:"Mobile,omitempty"`
	Data                 []byte   `protobuf:"bytes,2,opt,name=Data,proto3" json:"Data,omitempty"`
	FileName             string   `protobuf:"bytes,3,opt,name=FileName,proto3" json:"FileName,omitempty"`
	FileSize             int64    `protobuf:"varint,4,opt,name=FileSize,proto3" json:"FileSize,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *AvatarRequest) Reset()         { *m = AvatarRequest{} }
func (m *AvatarRequest) String() string { return proto.CompactTextString(m) }
func (*AvatarRequest) ProtoMessage()    {}
func (*AvatarRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_097b3f5db5cf5789, []int{11}
}

func (m *AvatarRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_AvatarRequest.Unmarshal(m, b)
}
func (m *AvatarRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_AvatarRequest.Marshal(b, m, deterministic)
}
func (m *AvatarRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_AvatarRequest.Merge(m, src)
}
func (m *AvatarRequest) XXX_Size() int {
	return xxx_messageInfo_AvatarRequest.Size(m)
}
func (m *AvatarRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_AvatarRequest.DiscardUnknown(m)
}

var xxx_messageInfo_AvatarRequest proto.InternalMessageInfo

func (m *AvatarRequest) GetMobile() string {
	if m != nil {
		return m.Mobile
	}
	return ""
}

func (m *AvatarRequest) GetData() []byte {
	if m != nil {
		return m.Data
	}
	return nil
}

func (m *AvatarRequest) GetFileName() string {
	if m != nil {
		return m.FileName
	}
	return ""
}

func (m *AvatarRequest) GetFileSize() int64 {
	if m != nil {
		return m.FileSize
	}
	return 0
}

type AvatarResponse struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *AvatarResponse) Reset()         { *m = AvatarResponse{} }
func (m *AvatarResponse) String() string { return proto.CompactTextString(m) }
func (*AvatarResponse) ProtoMessage()    {}
func (*AvatarResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_097b3f5db5cf5789, []int{12}
}

func (m *AvatarResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_AvatarResponse.Unmarshal(m, b)
}
func (m *AvatarResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_AvatarResponse.Marshal(b, m, deterministic)
}
func (m *AvatarResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_AvatarResponse.Merge(m, src)
}
func (m *AvatarResponse) XXX_Size() int {
	return xxx_messageInfo_AvatarResponse.Size(m)
}
func (m *AvatarResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_AvatarResponse.DiscardUnknown(m)
}

var xxx_messageInfo_AvatarResponse proto.InternalMessageInfo

type RenameRequest struct {
	Mobile               string   `protobuf:"bytes,1,opt,name=Mobile,proto3" json:"Mobile,omitempty"`
	NewName              string   `protobuf:"bytes,2,opt,name=NewName,proto3" json:"NewName,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *RenameRequest) Reset()         { *m = RenameRequest{} }
func (m *RenameRequest) String() string { return proto.CompactTextString(m) }
func (*RenameRequest) ProtoMessage()    {}
func (*RenameRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_097b3f5db5cf5789, []int{13}
}

func (m *RenameRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_RenameRequest.Unmarshal(m, b)
}
func (m *RenameRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_RenameRequest.Marshal(b, m, deterministic)
}
func (m *RenameRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_RenameRequest.Merge(m, src)
}
func (m *RenameRequest) XXX_Size() int {
	return xxx_messageInfo_RenameRequest.Size(m)
}
func (m *RenameRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_RenameRequest.DiscardUnknown(m)
}

var xxx_messageInfo_RenameRequest proto.InternalMessageInfo

func (m *RenameRequest) GetMobile() string {
	if m != nil {
		return m.Mobile
	}
	return ""
}

func (m *RenameRequest) GetNewName() string {
	if m != nil {
		return m.NewName
	}
	return ""
}

type RenameResponse struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *RenameResponse) Reset()         { *m = RenameResponse{} }
func (m *RenameResponse) String() string { return proto.CompactTextString(m) }
func (*RenameResponse) ProtoMessage()    {}
func (*RenameResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_097b3f5db5cf5789, []int{14}
}

func (m *RenameResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_RenameResponse.Unmarshal(m, b)
}
func (m *RenameResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_RenameResponse.Marshal(b, m, deterministic)
}
func (m *RenameResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_RenameResponse.Merge(m, src)
}
func (m *RenameResponse) XXX_Size() int {
	return xxx_messageInfo_RenameResponse.Size(m)
}
func (m *RenameResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_RenameResponse.DiscardUnknown(m)
}

var xxx_messageInfo_RenameResponse proto.InternalMessageInfo

type AuthRequest struct {
	Mobile               string   `protobuf:"bytes,1,opt,name=Mobile,proto3" json:"Mobile,omitempty"`
	RealName             string   `protobuf:"bytes,2,opt,name=RealName,proto3" json:"RealName,omitempty"`
	IdCard               string   `protobuf:"bytes,3,opt,name=IdCard,proto3" json:"IdCard,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *AuthRequest) Reset()         { *m = AuthRequest{} }
func (m *AuthRequest) String() string { return proto.CompactTextString(m) }
func (*AuthRequest) ProtoMessage()    {}
func (*AuthRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_097b3f5db5cf5789, []int{15}
}

func (m *AuthRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_AuthRequest.Unmarshal(m, b)
}
func (m *AuthRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_AuthRequest.Marshal(b, m, deterministic)
}
func (m *AuthRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_AuthRequest.Merge(m, src)
}
func (m *AuthRequest) XXX_Size() int {
	return xxx_messageInfo_AuthRequest.Size(m)
}
func (m *AuthRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_AuthRequest.DiscardUnknown(m)
}

var xxx_messageInfo_AuthRequest proto.InternalMessageInfo

func (m *AuthRequest) GetMobile() string {
	if m != nil {
		return m.Mobile
	}
	return ""
}

func (m *AuthRequest) GetRealName() string {
	if m != nil {
		return m.RealName
	}
	return ""
}

func (m *AuthRequest) GetIdCard() string {
	if m != nil {
		return m.IdCard
	}
	return ""
}

type AuthResponse struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *AuthResponse) Reset()         { *m = AuthResponse{} }
func (m *AuthResponse) String() string { return proto.CompactTextString(m) }
func (*AuthResponse) ProtoMessage()    {}
func (*AuthResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_097b3f5db5cf5789, []int{16}
}

func (m *AuthResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_AuthResponse.Unmarshal(m, b)
}
func (m *AuthResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_AuthResponse.Marshal(b, m, deterministic)
}
func (m *AuthResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_AuthResponse.Merge(m, src)
}
func (m *AuthResponse) XXX_Size() int {
	return xxx_messageInfo_AuthResponse.Size(m)
}
func (m *AuthResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_AuthResponse.DiscardUnknown(m)
}

var xxx_messageInfo_AuthResponse proto.InternalMessageInfo

func init() {
	proto.RegisterType((*Message)(nil), "go.micro.srv.user.Message")
	proto.RegisterType((*GenerateIdRequest)(nil), "go.micro.srv.user.GenerateIdRequest")
	proto.RegisterType((*GenerateIdResponse)(nil), "go.micro.srv.user.GenerateIdResponse")
	proto.RegisterType((*CaptchaRequest)(nil), "go.micro.srv.user.CaptchaRequest")
	proto.RegisterType((*CaptchaResponse)(nil), "go.micro.srv.user.CaptchaResponse")
	proto.RegisterType((*CaptchaResponse_Point)(nil), "go.micro.srv.user.CaptchaResponse.Point")
	proto.RegisterType((*SmsCaptchaRequest)(nil), "go.micro.srv.user.SmsCaptchaRequest")
	proto.RegisterType((*SmsCaptchaResponse)(nil), "go.micro.srv.user.SmsCaptchaResponse")
	proto.RegisterType((*RegisterRequest)(nil), "go.micro.srv.user.RegisterRequest")
	proto.RegisterType((*RegisterResponse)(nil), "go.micro.srv.user.RegisterResponse")
	proto.RegisterType((*GetInfoRequest)(nil), "go.micro.srv.user.GetInfoRequest")
	proto.RegisterType((*GetInfoResponse)(nil), "go.micro.srv.user.GetInfoResponse")
	proto.RegisterType((*AvatarRequest)(nil), "go.micro.srv.user.AvatarRequest")
	proto.RegisterType((*AvatarResponse)(nil), "go.micro.srv.user.AvatarResponse")
	proto.RegisterType((*RenameRequest)(nil), "go.micro.srv.user.RenameRequest")
	proto.RegisterType((*RenameResponse)(nil), "go.micro.srv.user.RenameResponse")
	proto.RegisterType((*AuthRequest)(nil), "go.micro.srv.user.AuthRequest")
	proto.RegisterType((*AuthResponse)(nil), "go.micro.srv.user.AuthResponse")
}

func init() { proto.RegisterFile("proto/example/example.proto", fileDescriptor_097b3f5db5cf5789) }

var fileDescriptor_097b3f5db5cf5789 = []byte{
	// 628 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x9c, 0x55, 0xdd, 0x6e, 0x12, 0x41,
	0x14, 0x66, 0xbb, 0xb4, 0x94, 0xd3, 0x3f, 0x18, 0x8d, 0xd9, 0x6c, 0x4d, 0xa5, 0x53, 0x9b, 0x70,
	0x61, 0xd6, 0xa4, 0xde, 0x79, 0x47, 0xaa, 0x36, 0xc4, 0x50, 0xc9, 0x90, 0x26, 0x25, 0xc6, 0x8b,
	0x01, 0x8e, 0x74, 0x13, 0xd8, 0xc5, 0x9d, 0x01, 0xa9, 0x57, 0xbe, 0x91, 0xaf, 0xe3, 0xe3, 0x98,
	0xd9, 0x9d, 0xfd, 0x01, 0x16, 0x50, 0xaf, 0x98, 0x73, 0xe6, 0x9c, 0xef, 0xfc, 0xf0, 0x7d, 0xb3,
	0x70, 0x3a, 0x09, 0x7c, 0xe9, 0xbf, 0xc6, 0x39, 0x1f, 0x4f, 0x46, 0x18, 0xff, 0x3a, 0xa1, 0x97,
	0x54, 0x87, 0xbe, 0x33, 0x76, 0xfb, 0x81, 0xef, 0x88, 0x60, 0xe6, 0x4c, 0x05, 0x06, 0xf4, 0x14,
	0x4a, 0x2d, 0x14, 0x82, 0x0f, 0x91, 0x54, 0xc0, 0x14, 0xfc, 0xd1, 0x32, 0x6a, 0x46, 0xbd, 0xcc,
	0xd4, 0x91, 0x3e, 0x81, 0xea, 0x0d, 0x7a, 0x18, 0x70, 0x89, 0xcd, 0x01, 0xc3, 0x6f, 0x53, 0x14,
	0x92, 0xbe, 0x02, 0x92, 0x75, 0x8a, 0x89, 0xef, 0x09, 0x24, 0xcf, 0x60, 0xef, 0x4e, 0x60, 0xd0,
	0x1c, 0xe8, 0x7c, 0x6d, 0xd1, 0x3a, 0x1c, 0x5f, 0xf3, 0x89, 0xec, 0x3f, 0x70, 0x9d, 0xbf, 0x36,
	0xf2, 0xb7, 0x01, 0x27, 0x49, 0xa8, 0x46, 0xad, 0x80, 0xd9, 0x76, 0xe7, 0x61, 0xe0, 0x21, 0x53,
	0x47, 0x95, 0xdd, 0x91, 0x81, 0x3b, 0x40, 0x6b, 0xa7, 0x66, 0xd4, 0x4d, 0xa6, 0x2d, 0xf2, 0x16,
	0xcc, 0x96, 0xeb, 0x59, 0x66, 0xcd, 0xa8, 0x1f, 0x5c, 0xd5, 0x9d, 0x95, 0x41, 0x9d, 0x25, 0x68,
	0xa7, 0xed, 0xbb, 0x9e, 0x64, 0x2a, 0x29, 0xcc, 0xe5, 0x73, 0xab, 0xf8, 0xcf, 0xb9, 0x7c, 0x6e,
	0x5f, 0xc0, 0x6e, 0x68, 0x91, 0x43, 0x30, 0xee, 0xc3, 0x46, 0x4d, 0x66, 0xdc, 0x2b, 0xab, 0xab,
	0x3b, 0x34, 0xba, 0xf4, 0x0b, 0x54, 0x3b, 0x63, 0xf1, 0x77, 0x7b, 0x50, 0xfe, 0x96, 0xdf, 0x73,
	0x47, 0xd1, 0x84, 0x65, 0xa6, 0x2d, 0x62, 0x41, 0x49, 0x23, 0x84, 0x53, 0x96, 0x59, 0x6c, 0xd2,
	0xa7, 0x40, 0xb2, 0xf0, 0x51, 0x93, 0x94, 0xc3, 0x09, 0xc3, 0xa1, 0x2b, 0x24, 0x06, 0xff, 0x5b,
	0xf2, 0x0c, 0x20, 0x05, 0xd6, 0x55, 0x33, 0x1e, 0xfa, 0xd3, 0x80, 0x4a, 0x5a, 0x63, 0x33, 0x13,
	0xd6, 0x16, 0x79, 0x0e, 0xe5, 0xf6, 0xb4, 0x37, 0x72, 0xfb, 0x1f, 0xf1, 0x51, 0xd7, 0x48, 0x1d,
	0xaa, 0x85, 0x76, 0xe0, 0xce, 0xb8, 0x44, 0x75, 0x5d, 0x8c, 0x5a, 0x48, 0x3d, 0x8a, 0x5f, 0x37,
	0x28, 0x9b, 0xde, 0x57, 0x3f, 0x33, 0xa4, 0xae, 0x63, 0x64, 0xeb, 0xd0, 0x4b, 0x38, 0x49, 0x22,
	0x75, 0xab, 0x04, 0x8a, 0xef, 0xb8, 0xe4, 0x9a, 0x5f, 0xe1, 0x99, 0x0a, 0x38, 0x6a, 0xcc, 0xb8,
	0xe4, 0xc1, 0x16, 0xbc, 0x24, 0x79, 0x27, 0x4d, 0x26, 0x36, 0xec, 0x7f, 0x70, 0x47, 0x78, 0xcb,
	0xc7, 0xa8, 0x47, 0x49, 0xec, 0xf8, 0xae, 0xe3, 0xfe, 0xc0, 0x70, 0x0e, 0x93, 0x25, 0x36, 0xad,
	0xc0, 0x71, 0x5c, 0x54, 0xff, 0x7b, 0x0d, 0x38, 0x62, 0xe8, 0xf1, 0x31, 0x6e, 0x6b, 0xc3, 0x82,
	0xd2, 0x2d, 0x7e, 0x0f, 0x2b, 0x46, 0x7b, 0x8d, 0x4d, 0x05, 0x1a, 0x43, 0x68, 0xd0, 0x2e, 0x1c,
	0x34, 0xa6, 0xf2, 0x61, 0x1b, 0xa4, 0x0d, 0xfb, 0x0c, 0xf9, 0x28, 0x83, 0x99, 0xd8, 0x2a, 0xa7,
	0x39, 0xb8, 0xe6, 0xc1, 0x40, 0xcf, 0xa7, 0x2d, 0x7a, 0x0c, 0x87, 0x11, 0x74, 0x54, 0xea, 0xea,
	0xd7, 0x2e, 0x94, 0xde, 0x47, 0x8f, 0x0f, 0xf9, 0x0c, 0x90, 0xbe, 0x18, 0xe4, 0x65, 0x8e, 0xc0,
	0x56, 0x5e, 0x19, 0xfb, 0x72, 0x4b, 0x94, 0x9e, 0xa8, 0x40, 0x58, 0x22, 0x0b, 0x72, 0xbe, 0x49,
	0xba, 0x11, 0x2c, 0xdd, 0xae, 0x6e, 0x5a, 0x50, 0x0d, 0xa7, 0x2c, 0xcf, 0x6d, 0x78, 0x45, 0xce,
	0xb9, 0x0d, 0xe7, 0xa8, 0xb2, 0x40, 0xee, 0xd4, 0x76, 0x23, 0xcd, 0x90, 0xbc, 0x76, 0x96, 0x44,
	0x6b, 0x5f, 0x6c, 0x8c, 0xc9, 0xee, 0x41, 0xd3, 0x3b, 0x77, 0x0f, 0x8b, 0x22, 0xc9, 0xdd, 0xc3,
	0x92, 0x3a, 0x68, 0x81, 0x7c, 0x82, 0xbd, 0x88, 0x96, 0xa4, 0x96, 0x13, 0xbf, 0x20, 0x13, 0xfb,
	0x7c, 0x43, 0x44, 0x16, 0x30, 0xa2, 0x64, 0x2e, 0xe0, 0x02, 0xe1, 0x73, 0x01, 0x97, 0xf8, 0x5c,
	0x20, 0x4d, 0x28, 0x2a, 0xda, 0x91, 0xb3, 0xbc, 0xea, 0x29, 0xd5, 0xed, 0x17, 0x6b, 0xef, 0x63,
	0xa8, 0xde, 0x5e, 0xf8, 0x8d, 0x7c, 0xf3, 0x27, 0x00, 0x00, 0xff, 0xff, 0x21, 0xdd, 0x07, 0x93,
	0x42, 0x07, 0x00, 0x00,
}
