// Code generated by protoc-gen-go. DO NOT EDIT.
// source: proto/example/example.proto

package go_micro_srv_order

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type Message struct {
	Say                  string   `protobuf:"bytes,1,opt,name=say,proto3" json:"say,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Message) Reset()         { *m = Message{} }
func (m *Message) String() string { return proto.CompactTextString(m) }
func (*Message) ProtoMessage()    {}
func (*Message) Descriptor() ([]byte, []int) {
	return fileDescriptor_097b3f5db5cf5789, []int{0}
}

func (m *Message) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Message.Unmarshal(m, b)
}
func (m *Message) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Message.Marshal(b, m, deterministic)
}
func (m *Message) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Message.Merge(m, src)
}
func (m *Message) XXX_Size() int {
	return xxx_messageInfo_Message.Size(m)
}
func (m *Message) XXX_DiscardUnknown() {
	xxx_messageInfo_Message.DiscardUnknown(m)
}

var xxx_messageInfo_Message proto.InternalMessageInfo

func (m *Message) GetSay() string {
	if m != nil {
		return m.Say
	}
	return ""
}

type AddRequest struct {
	Mobile               string   `protobuf:"bytes,1,opt,name=Mobile,proto3" json:"Mobile,omitempty"`
	Data                 []byte   `protobuf:"bytes,2,opt,name=Data,proto3" json:"Data,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *AddRequest) Reset()         { *m = AddRequest{} }
func (m *AddRequest) String() string { return proto.CompactTextString(m) }
func (*AddRequest) ProtoMessage()    {}
func (*AddRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_097b3f5db5cf5789, []int{1}
}

func (m *AddRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_AddRequest.Unmarshal(m, b)
}
func (m *AddRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_AddRequest.Marshal(b, m, deterministic)
}
func (m *AddRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_AddRequest.Merge(m, src)
}
func (m *AddRequest) XXX_Size() int {
	return xxx_messageInfo_AddRequest.Size(m)
}
func (m *AddRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_AddRequest.DiscardUnknown(m)
}

var xxx_messageInfo_AddRequest proto.InternalMessageInfo

func (m *AddRequest) GetMobile() string {
	if m != nil {
		return m.Mobile
	}
	return ""
}

func (m *AddRequest) GetData() []byte {
	if m != nil {
		return m.Data
	}
	return nil
}

type AddResponse struct {
	Code                 string   `protobuf:"bytes,1,opt,name=Code,proto3" json:"Code,omitempty"`
	Msg                  string   `protobuf:"bytes,2,opt,name=Msg,proto3" json:"Msg,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *AddResponse) Reset()         { *m = AddResponse{} }
func (m *AddResponse) String() string { return proto.CompactTextString(m) }
func (*AddResponse) ProtoMessage()    {}
func (*AddResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_097b3f5db5cf5789, []int{2}
}

func (m *AddResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_AddResponse.Unmarshal(m, b)
}
func (m *AddResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_AddResponse.Marshal(b, m, deterministic)
}
func (m *AddResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_AddResponse.Merge(m, src)
}
func (m *AddResponse) XXX_Size() int {
	return xxx_messageInfo_AddResponse.Size(m)
}
func (m *AddResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_AddResponse.DiscardUnknown(m)
}

var xxx_messageInfo_AddResponse proto.InternalMessageInfo

func (m *AddResponse) GetCode() string {
	if m != nil {
		return m.Code
	}
	return ""
}

func (m *AddResponse) GetMsg() string {
	if m != nil {
		return m.Msg
	}
	return ""
}

type GetListRequest struct {
	Mobile               string   `protobuf:"bytes,1,opt,name=Mobile,proto3" json:"Mobile,omitempty"`
	Role                 string   `protobuf:"bytes,2,opt,name=Role,proto3" json:"Role,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetListRequest) Reset()         { *m = GetListRequest{} }
func (m *GetListRequest) String() string { return proto.CompactTextString(m) }
func (*GetListRequest) ProtoMessage()    {}
func (*GetListRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_097b3f5db5cf5789, []int{3}
}

func (m *GetListRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetListRequest.Unmarshal(m, b)
}
func (m *GetListRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetListRequest.Marshal(b, m, deterministic)
}
func (m *GetListRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetListRequest.Merge(m, src)
}
func (m *GetListRequest) XXX_Size() int {
	return xxx_messageInfo_GetListRequest.Size(m)
}
func (m *GetListRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_GetListRequest.DiscardUnknown(m)
}

var xxx_messageInfo_GetListRequest proto.InternalMessageInfo

func (m *GetListRequest) GetMobile() string {
	if m != nil {
		return m.Mobile
	}
	return ""
}

func (m *GetListRequest) GetRole() string {
	if m != nil {
		return m.Role
	}
	return ""
}

type GetListResponse struct {
	Code                 string   `protobuf:"bytes,1,opt,name=Code,proto3" json:"Code,omitempty"`
	Msg                  string   `protobuf:"bytes,2,opt,name=Msg,proto3" json:"Msg,omitempty"`
	Data                 []byte   `protobuf:"bytes,3,opt,name=Data,proto3" json:"Data,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetListResponse) Reset()         { *m = GetListResponse{} }
func (m *GetListResponse) String() string { return proto.CompactTextString(m) }
func (*GetListResponse) ProtoMessage()    {}
func (*GetListResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_097b3f5db5cf5789, []int{4}
}

func (m *GetListResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetListResponse.Unmarshal(m, b)
}
func (m *GetListResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetListResponse.Marshal(b, m, deterministic)
}
func (m *GetListResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetListResponse.Merge(m, src)
}
func (m *GetListResponse) XXX_Size() int {
	return xxx_messageInfo_GetListResponse.Size(m)
}
func (m *GetListResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_GetListResponse.DiscardUnknown(m)
}

var xxx_messageInfo_GetListResponse proto.InternalMessageInfo

func (m *GetListResponse) GetCode() string {
	if m != nil {
		return m.Code
	}
	return ""
}

func (m *GetListResponse) GetMsg() string {
	if m != nil {
		return m.Msg
	}
	return ""
}

func (m *GetListResponse) GetData() []byte {
	if m != nil {
		return m.Data
	}
	return nil
}

type HandleRequest struct {
	Mobile               string   `protobuf:"bytes,1,opt,name=Mobile,proto3" json:"Mobile,omitempty"`
	OrderId              string   `protobuf:"bytes,2,opt,name=OrderId,proto3" json:"OrderId,omitempty"`
	Action               string   `protobuf:"bytes,3,opt,name=Action,proto3" json:"Action,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *HandleRequest) Reset()         { *m = HandleRequest{} }
func (m *HandleRequest) String() string { return proto.CompactTextString(m) }
func (*HandleRequest) ProtoMessage()    {}
func (*HandleRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_097b3f5db5cf5789, []int{5}
}

func (m *HandleRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_HandleRequest.Unmarshal(m, b)
}
func (m *HandleRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_HandleRequest.Marshal(b, m, deterministic)
}
func (m *HandleRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_HandleRequest.Merge(m, src)
}
func (m *HandleRequest) XXX_Size() int {
	return xxx_messageInfo_HandleRequest.Size(m)
}
func (m *HandleRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_HandleRequest.DiscardUnknown(m)
}

var xxx_messageInfo_HandleRequest proto.InternalMessageInfo

func (m *HandleRequest) GetMobile() string {
	if m != nil {
		return m.Mobile
	}
	return ""
}

func (m *HandleRequest) GetOrderId() string {
	if m != nil {
		return m.OrderId
	}
	return ""
}

func (m *HandleRequest) GetAction() string {
	if m != nil {
		return m.Action
	}
	return ""
}

type HandleResponse struct {
	Code                 string   `protobuf:"bytes,1,opt,name=Code,proto3" json:"Code,omitempty"`
	Msg                  string   `protobuf:"bytes,2,opt,name=Msg,proto3" json:"Msg,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *HandleResponse) Reset()         { *m = HandleResponse{} }
func (m *HandleResponse) String() string { return proto.CompactTextString(m) }
func (*HandleResponse) ProtoMessage()    {}
func (*HandleResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_097b3f5db5cf5789, []int{6}
}

func (m *HandleResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_HandleResponse.Unmarshal(m, b)
}
func (m *HandleResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_HandleResponse.Marshal(b, m, deterministic)
}
func (m *HandleResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_HandleResponse.Merge(m, src)
}
func (m *HandleResponse) XXX_Size() int {
	return xxx_messageInfo_HandleResponse.Size(m)
}
func (m *HandleResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_HandleResponse.DiscardUnknown(m)
}

var xxx_messageInfo_HandleResponse proto.InternalMessageInfo

func (m *HandleResponse) GetCode() string {
	if m != nil {
		return m.Code
	}
	return ""
}

func (m *HandleResponse) GetMsg() string {
	if m != nil {
		return m.Msg
	}
	return ""
}

type CommentRequest struct {
	Mobile               string   `protobuf:"bytes,1,opt,name=Mobile,proto3" json:"Mobile,omitempty"`
	OrderId              string   `protobuf:"bytes,2,opt,name=OrderId,proto3" json:"OrderId,omitempty"`
	Comment              string   `protobuf:"bytes,3,opt,name=Comment,proto3" json:"Comment,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *CommentRequest) Reset()         { *m = CommentRequest{} }
func (m *CommentRequest) String() string { return proto.CompactTextString(m) }
func (*CommentRequest) ProtoMessage()    {}
func (*CommentRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_097b3f5db5cf5789, []int{7}
}

func (m *CommentRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CommentRequest.Unmarshal(m, b)
}
func (m *CommentRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CommentRequest.Marshal(b, m, deterministic)
}
func (m *CommentRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CommentRequest.Merge(m, src)
}
func (m *CommentRequest) XXX_Size() int {
	return xxx_messageInfo_CommentRequest.Size(m)
}
func (m *CommentRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_CommentRequest.DiscardUnknown(m)
}

var xxx_messageInfo_CommentRequest proto.InternalMessageInfo

func (m *CommentRequest) GetMobile() string {
	if m != nil {
		return m.Mobile
	}
	return ""
}

func (m *CommentRequest) GetOrderId() string {
	if m != nil {
		return m.OrderId
	}
	return ""
}

func (m *CommentRequest) GetComment() string {
	if m != nil {
		return m.Comment
	}
	return ""
}

type CommentResponse struct {
	Code                 string   `protobuf:"bytes,1,opt,name=Code,proto3" json:"Code,omitempty"`
	Msg                  string   `protobuf:"bytes,2,opt,name=Msg,proto3" json:"Msg,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *CommentResponse) Reset()         { *m = CommentResponse{} }
func (m *CommentResponse) String() string { return proto.CompactTextString(m) }
func (*CommentResponse) ProtoMessage()    {}
func (*CommentResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_097b3f5db5cf5789, []int{8}
}

func (m *CommentResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CommentResponse.Unmarshal(m, b)
}
func (m *CommentResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CommentResponse.Marshal(b, m, deterministic)
}
func (m *CommentResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CommentResponse.Merge(m, src)
}
func (m *CommentResponse) XXX_Size() int {
	return xxx_messageInfo_CommentResponse.Size(m)
}
func (m *CommentResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_CommentResponse.DiscardUnknown(m)
}

var xxx_messageInfo_CommentResponse proto.InternalMessageInfo

func (m *CommentResponse) GetCode() string {
	if m != nil {
		return m.Code
	}
	return ""
}

func (m *CommentResponse) GetMsg() string {
	if m != nil {
		return m.Msg
	}
	return ""
}

func init() {
	proto.RegisterType((*Message)(nil), "go.micro.srv.order.Message")
	proto.RegisterType((*AddRequest)(nil), "go.micro.srv.order.AddRequest")
	proto.RegisterType((*AddResponse)(nil), "go.micro.srv.order.AddResponse")
	proto.RegisterType((*GetListRequest)(nil), "go.micro.srv.order.GetListRequest")
	proto.RegisterType((*GetListResponse)(nil), "go.micro.srv.order.GetListResponse")
	proto.RegisterType((*HandleRequest)(nil), "go.micro.srv.order.HandleRequest")
	proto.RegisterType((*HandleResponse)(nil), "go.micro.srv.order.HandleResponse")
	proto.RegisterType((*CommentRequest)(nil), "go.micro.srv.order.CommentRequest")
	proto.RegisterType((*CommentResponse)(nil), "go.micro.srv.order.CommentResponse")
}

func init() { proto.RegisterFile("proto/example/example.proto", fileDescriptor_097b3f5db5cf5789) }

var fileDescriptor_097b3f5db5cf5789 = []byte{
	// 358 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x9c, 0x53, 0x4f, 0x4b, 0xfb, 0x40,
	0x10, 0xed, 0x9f, 0x1f, 0x0d, 0x9d, 0x9f, 0xb6, 0xb2, 0x07, 0x09, 0x2d, 0x68, 0x5d, 0x2f, 0x3d,
	0xad, 0x60, 0x41, 0x3d, 0x78, 0x29, 0x55, 0xac, 0x68, 0x11, 0x17, 0x2f, 0x82, 0x97, 0x6d, 0x77,
	0x28, 0x81, 0x24, 0x5b, 0xb3, 0xab, 0xe8, 0xd7, 0xf4, 0x13, 0x49, 0xb6, 0x9b, 0xd8, 0x6a, 0xac,
	0xd6, 0x53, 0x66, 0x92, 0xf7, 0xde, 0x3c, 0xde, 0x4c, 0xa0, 0x3d, 0x4b, 0x94, 0x51, 0x07, 0xf8,
	0x22, 0xa2, 0x59, 0x88, 0xd9, 0x93, 0xd9, 0xb7, 0x84, 0x4c, 0x15, 0x8b, 0x82, 0x49, 0xa2, 0x98,
	0x4e, 0x9e, 0x99, 0x4a, 0x24, 0x26, 0xb4, 0x0d, 0xde, 0x08, 0xb5, 0x16, 0x53, 0x24, 0x5b, 0x50,
	0xd5, 0xe2, 0xd5, 0x2f, 0x77, 0xca, 0xdd, 0x3a, 0x4f, 0x4b, 0x7a, 0x02, 0xd0, 0x97, 0x92, 0xe3,
	0xe3, 0x13, 0x6a, 0x43, 0xb6, 0xa1, 0x36, 0x52, 0xe3, 0x20, 0x44, 0x07, 0x71, 0x1d, 0x21, 0xf0,
	0xef, 0x4c, 0x18, 0xe1, 0x57, 0x3a, 0xe5, 0xee, 0x06, 0xb7, 0x35, 0xed, 0xc1, 0x7f, 0xcb, 0xd4,
	0x33, 0x15, 0x6b, 0x0b, 0x19, 0x28, 0x99, 0x11, 0x6d, 0x9d, 0x8e, 0x1b, 0xe9, 0xa9, 0x65, 0xd5,
	0x79, 0x5a, 0xd2, 0x53, 0x68, 0x5c, 0xa0, 0xb9, 0x0e, 0xb4, 0xf9, 0xc5, 0x48, 0xae, 0x42, 0x74,
	0x64, 0x5b, 0xd3, 0x2b, 0x68, 0xe6, 0xec, 0x75, 0xc6, 0xe6, 0xfe, 0xab, 0x0b, 0xfe, 0xef, 0x61,
	0x73, 0x28, 0x62, 0x19, 0xe2, 0x4f, 0x4e, 0x7c, 0xf0, 0x6e, 0xd2, 0x20, 0x2f, 0xa5, 0x93, 0xcc,
	0xda, 0x94, 0xd1, 0x9f, 0x98, 0x40, 0xc5, 0x56, 0xb8, 0xce, 0x5d, 0x47, 0x8f, 0xa0, 0x91, 0x49,
	0xaf, 0x95, 0xce, 0x03, 0x34, 0x06, 0x2a, 0x8a, 0x30, 0x36, 0x7f, 0xf7, 0xe4, 0x83, 0xe7, 0x34,
	0x9c, 0xa9, 0xac, 0xa5, 0xc7, 0xd0, 0xcc, 0xd5, 0xd7, 0xb1, 0x75, 0xf8, 0x56, 0x01, 0xef, 0x7c,
	0x7e, 0x66, 0x64, 0x08, 0xd5, 0xbe, 0x94, 0x64, 0x87, 0x7d, 0x3d, 0x34, 0xf6, 0x71, 0x48, 0xad,
	0xdd, 0x6f, 0xbf, 0xcf, 0x27, 0xd3, 0x12, 0xb9, 0x03, 0xcf, 0x2d, 0x93, 0xd0, 0x22, 0xf4, 0xf2,
	0x9d, 0xb4, 0xf6, 0x57, 0x62, 0x72, 0xd5, 0x5b, 0xa8, 0xcd, 0xa3, 0x27, 0x7b, 0x45, 0x84, 0xa5,
	0x8d, 0xb7, 0xe8, 0x2a, 0xc8, 0xa2, 0x51, 0x97, 0x5b, 0xb1, 0xd1, 0xe5, 0x95, 0x15, 0x1b, 0xfd,
	0x14, 0x3c, 0x2d, 0x8d, 0x6b, 0xf6, 0x87, 0xed, 0xbd, 0x07, 0x00, 0x00, 0xff, 0xff, 0xdf, 0x2b,
	0x10, 0x7b, 0xcf, 0x03, 0x00, 0x00,
}
