// Code generated by protoc-gen-go. DO NOT EDIT.
// source: proto/example/example.proto

package go_micro_srv_GetArea

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type Message struct {
	Say                  string   `protobuf:"bytes,1,opt,name=say,proto3" json:"say,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Message) Reset()         { *m = Message{} }
func (m *Message) String() string { return proto.CompactTextString(m) }
func (*Message) ProtoMessage()    {}
func (*Message) Descriptor() ([]byte, []int) {
	return fileDescriptor_097b3f5db5cf5789, []int{0}
}

func (m *Message) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Message.Unmarshal(m, b)
}
func (m *Message) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Message.Marshal(b, m, deterministic)
}
func (m *Message) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Message.Merge(m, src)
}
func (m *Message) XXX_Size() int {
	return xxx_messageInfo_Message.Size(m)
}
func (m *Message) XXX_DiscardUnknown() {
	xxx_messageInfo_Message.DiscardUnknown(m)
}

var xxx_messageInfo_Message proto.InternalMessageInfo

func (m *Message) GetSay() string {
	if m != nil {
		return m.Say
	}
	return ""
}

type Request struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Request) Reset()         { *m = Request{} }
func (m *Request) String() string { return proto.CompactTextString(m) }
func (*Request) ProtoMessage()    {}
func (*Request) Descriptor() ([]byte, []int) {
	return fileDescriptor_097b3f5db5cf5789, []int{1}
}

func (m *Request) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Request.Unmarshal(m, b)
}
func (m *Request) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Request.Marshal(b, m, deterministic)
}
func (m *Request) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Request.Merge(m, src)
}
func (m *Request) XXX_Size() int {
	return xxx_messageInfo_Request.Size(m)
}
func (m *Request) XXX_DiscardUnknown() {
	xxx_messageInfo_Request.DiscardUnknown(m)
}

var xxx_messageInfo_Request proto.InternalMessageInfo

type Response struct {
	ErrCode              string           `protobuf:"bytes,1,opt,name=ErrCode,proto3" json:"ErrCode,omitempty"`
	ErrMsg               string           `protobuf:"bytes,2,opt,name=ErrMsg,proto3" json:"ErrMsg,omitempty"`
	Data                 []*Response_Area `protobuf:"bytes,3,rep,name=Data,proto3" json:"Data,omitempty"`
	XXX_NoUnkeyedLiteral struct{}         `json:"-"`
	XXX_unrecognized     []byte           `json:"-"`
	XXX_sizecache        int32            `json:"-"`
}

func (m *Response) Reset()         { *m = Response{} }
func (m *Response) String() string { return proto.CompactTextString(m) }
func (*Response) ProtoMessage()    {}
func (*Response) Descriptor() ([]byte, []int) {
	return fileDescriptor_097b3f5db5cf5789, []int{2}
}

func (m *Response) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Response.Unmarshal(m, b)
}
func (m *Response) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Response.Marshal(b, m, deterministic)
}
func (m *Response) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Response.Merge(m, src)
}
func (m *Response) XXX_Size() int {
	return xxx_messageInfo_Response.Size(m)
}
func (m *Response) XXX_DiscardUnknown() {
	xxx_messageInfo_Response.DiscardUnknown(m)
}

var xxx_messageInfo_Response proto.InternalMessageInfo

func (m *Response) GetErrCode() string {
	if m != nil {
		return m.ErrCode
	}
	return ""
}

func (m *Response) GetErrMsg() string {
	if m != nil {
		return m.ErrMsg
	}
	return ""
}

func (m *Response) GetData() []*Response_Area {
	if m != nil {
		return m.Data
	}
	return nil
}

type Response_Area struct {
	Id                   int32    `protobuf:"varint,1,opt,name=Id,proto3" json:"Id,omitempty"`
	Name                 string   `protobuf:"bytes,2,opt,name=Name,proto3" json:"Name,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Response_Area) Reset()         { *m = Response_Area{} }
func (m *Response_Area) String() string { return proto.CompactTextString(m) }
func (*Response_Area) ProtoMessage()    {}
func (*Response_Area) Descriptor() ([]byte, []int) {
	return fileDescriptor_097b3f5db5cf5789, []int{2, 0}
}

func (m *Response_Area) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Response_Area.Unmarshal(m, b)
}
func (m *Response_Area) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Response_Area.Marshal(b, m, deterministic)
}
func (m *Response_Area) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Response_Area.Merge(m, src)
}
func (m *Response_Area) XXX_Size() int {
	return xxx_messageInfo_Response_Area.Size(m)
}
func (m *Response_Area) XXX_DiscardUnknown() {
	xxx_messageInfo_Response_Area.DiscardUnknown(m)
}

var xxx_messageInfo_Response_Area proto.InternalMessageInfo

func (m *Response_Area) GetId() int32 {
	if m != nil {
		return m.Id
	}
	return 0
}

func (m *Response_Area) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func init() {
	proto.RegisterType((*Message)(nil), "go.micro.srv.GetArea.Message")
	proto.RegisterType((*Request)(nil), "go.micro.srv.GetArea.Request")
	proto.RegisterType((*Response)(nil), "go.micro.srv.GetArea.Response")
	proto.RegisterType((*Response_Area)(nil), "go.micro.srv.GetArea.Response.Area")
}

func init() { proto.RegisterFile("proto/example/example.proto", fileDescriptor_097b3f5db5cf5789) }

var fileDescriptor_097b3f5db5cf5789 = []byte{
	// 236 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x7c, 0x90, 0xcd, 0x4a, 0x03, 0x31,
	0x10, 0xc7, 0xdd, 0x0f, 0x1b, 0x3b, 0x82, 0xc8, 0x20, 0xb2, 0xb4, 0x28, 0x25, 0x5e, 0x8a, 0x87,
	0x08, 0xf5, 0xe0, 0x59, 0x74, 0x91, 0x0a, 0xf5, 0x10, 0xf0, 0x01, 0xa2, 0x3b, 0x2c, 0x82, 0x6b,
	0xd6, 0x99, 0x28, 0xfa, 0x38, 0xbe, 0xa9, 0x6c, 0xcc, 0xde, 0xd4, 0x53, 0xe6, 0x97, 0x8f, 0xff,
	0x47, 0x60, 0xde, 0xb3, 0x0f, 0xfe, 0x8c, 0x3e, 0x5c, 0xd7, 0x3f, 0xd3, 0xb8, 0x9a, 0xb8, 0x8b,
	0x07, 0xad, 0x37, 0xdd, 0xd3, 0x23, 0x7b, 0x23, 0xfc, 0x6e, 0x6e, 0x28, 0x5c, 0x32, 0x39, 0x3d,
	0x07, 0xb5, 0x21, 0x11, 0xd7, 0x12, 0xee, 0x43, 0x21, 0xee, 0xb3, 0xca, 0x16, 0xd9, 0x72, 0x6a,
	0x87, 0x51, 0x4f, 0x41, 0x59, 0x7a, 0x7d, 0x23, 0x09, 0xfa, 0x2b, 0x83, 0x1d, 0x4b, 0xd2, 0xfb,
	0x17, 0x21, 0xac, 0x40, 0xd5, 0xcc, 0x57, 0xbe, 0xa1, 0x74, 0x7b, 0x44, 0x3c, 0x84, 0x49, 0xcd,
	0xbc, 0x91, 0xb6, 0xca, 0xe3, 0x41, 0x22, 0xbc, 0x80, 0xf2, 0xda, 0x05, 0x57, 0x15, 0x8b, 0x62,
	0xb9, 0xbb, 0x3a, 0x31, 0xbf, 0x65, 0x31, 0xa3, 0xbe, 0x19, 0xc8, 0xc6, 0x07, 0xb3, 0x53, 0x28,
	0x07, 0xc2, 0x3d, 0xc8, 0xd7, 0x4d, 0x74, 0xdb, 0xb6, 0xf9, 0xba, 0x41, 0x84, 0xf2, 0xce, 0x75,
	0x94, 0x6c, 0xe2, 0xbc, 0xba, 0x07, 0x55, 0xff, 0x54, 0xc6, 0x5b, 0x50, 0x49, 0x15, 0x8f, 0xfe,
	0x32, 0x8b, 0xc5, 0x66, 0xc7, 0xff, 0x67, 0xd1, 0x5b, 0x0f, 0x93, 0xf8, 0x7f, 0xe7, 0xdf, 0x01,
	0x00, 0x00, 0xff, 0xff, 0xf0, 0x62, 0x8c, 0x43, 0x5e, 0x01, 0x00, 0x00,
}
