// Code generated by protoc-gen-micro. DO NOT EDIT.
// source: proto/example/example.proto

/*
Package go_micro_srv_house is a generated protocol buffer package.

It is generated from these files:
	proto/example/example.proto

It has these top-level messages:
	Message
	AddRequest
	AddResponse
	GetHouseListRequest
	GetHouseListResponse
	GetHouseDescRequest
	GetHouseDescResponse
	UploadImageRequest
	UploadImageResponse
	GetIndexListRequest
	GetIndexListResponse
*/
package go_micro_srv_house

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

import (
	context "context"
	client "github.com/micro/go-micro/client"
	server "github.com/micro/go-micro/server"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ client.Option
var _ server.Option

// Client API for Example service

type ExampleService interface {
	Add(ctx context.Context, in *AddRequest, opts ...client.CallOption) (*AddResponse, error)
	GetHouseList(ctx context.Context, in *GetHouseListRequest, opts ...client.CallOption) (*GetHouseListResponse, error)
	GetHouseDesc(ctx context.Context, in *GetHouseDescRequest, opts ...client.CallOption) (*GetHouseDescResponse, error)
	UploadImage(ctx context.Context, in *UploadImageRequest, opts ...client.CallOption) (*UploadImageResponse, error)
	GetIndexList(ctx context.Context, in *GetIndexListRequest, opts ...client.CallOption) (*GetIndexListResponse, error)
}

type exampleService struct {
	c    client.Client
	name string
}

func NewExampleService(name string, c client.Client) ExampleService {
	if c == nil {
		c = client.NewClient()
	}
	if len(name) == 0 {
		name = "go.micro.srv.house"
	}
	return &exampleService{
		c:    c,
		name: name,
	}
}

func (c *exampleService) Add(ctx context.Context, in *AddRequest, opts ...client.CallOption) (*AddResponse, error) {
	req := c.c.NewRequest(c.name, "Example.Add", in)
	out := new(AddResponse)
	err := c.c.Call(ctx, req, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *exampleService) GetHouseList(ctx context.Context, in *GetHouseListRequest, opts ...client.CallOption) (*GetHouseListResponse, error) {
	req := c.c.NewRequest(c.name, "Example.GetHouseList", in)
	out := new(GetHouseListResponse)
	err := c.c.Call(ctx, req, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *exampleService) GetHouseDesc(ctx context.Context, in *GetHouseDescRequest, opts ...client.CallOption) (*GetHouseDescResponse, error) {
	req := c.c.NewRequest(c.name, "Example.GetHouseDesc", in)
	out := new(GetHouseDescResponse)
	err := c.c.Call(ctx, req, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *exampleService) UploadImage(ctx context.Context, in *UploadImageRequest, opts ...client.CallOption) (*UploadImageResponse, error) {
	req := c.c.NewRequest(c.name, "Example.UploadImage", in)
	out := new(UploadImageResponse)
	err := c.c.Call(ctx, req, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *exampleService) GetIndexList(ctx context.Context, in *GetIndexListRequest, opts ...client.CallOption) (*GetIndexListResponse, error) {
	req := c.c.NewRequest(c.name, "Example.GetIndexList", in)
	out := new(GetIndexListResponse)
	err := c.c.Call(ctx, req, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// Server API for Example service

type ExampleHandler interface {
	Add(context.Context, *AddRequest, *AddResponse) error
	GetHouseList(context.Context, *GetHouseListRequest, *GetHouseListResponse) error
	GetHouseDesc(context.Context, *GetHouseDescRequest, *GetHouseDescResponse) error
	UploadImage(context.Context, *UploadImageRequest, *UploadImageResponse) error
	GetIndexList(context.Context, *GetIndexListRequest, *GetIndexListResponse) error
}

func RegisterExampleHandler(s server.Server, hdlr ExampleHandler, opts ...server.HandlerOption) error {
	type example interface {
		Add(ctx context.Context, in *AddRequest, out *AddResponse) error
		GetHouseList(ctx context.Context, in *GetHouseListRequest, out *GetHouseListResponse) error
		GetHouseDesc(ctx context.Context, in *GetHouseDescRequest, out *GetHouseDescResponse) error
		UploadImage(ctx context.Context, in *UploadImageRequest, out *UploadImageResponse) error
		GetIndexList(ctx context.Context, in *GetIndexListRequest, out *GetIndexListResponse) error
	}
	type Example struct {
		example
	}
	h := &exampleHandler{hdlr}
	return s.Handle(s.NewHandler(&Example{h}, opts...))
}

type exampleHandler struct {
	ExampleHandler
}

func (h *exampleHandler) Add(ctx context.Context, in *AddRequest, out *AddResponse) error {
	return h.ExampleHandler.Add(ctx, in, out)
}

func (h *exampleHandler) GetHouseList(ctx context.Context, in *GetHouseListRequest, out *GetHouseListResponse) error {
	return h.ExampleHandler.GetHouseList(ctx, in, out)
}

func (h *exampleHandler) GetHouseDesc(ctx context.Context, in *GetHouseDescRequest, out *GetHouseDescResponse) error {
	return h.ExampleHandler.GetHouseDesc(ctx, in, out)
}

func (h *exampleHandler) UploadImage(ctx context.Context, in *UploadImageRequest, out *UploadImageResponse) error {
	return h.ExampleHandler.UploadImage(ctx, in, out)
}

func (h *exampleHandler) GetIndexList(ctx context.Context, in *GetIndexListRequest, out *GetIndexListResponse) error {
	return h.ExampleHandler.GetIndexList(ctx, in, out)
}
