// Code generated by protoc-gen-go. DO NOT EDIT.
// source: proto/example/example.proto

package go_micro_srv_house

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type Message struct {
	Say                  string   `protobuf:"bytes,1,opt,name=say,proto3" json:"say,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Message) Reset()         { *m = Message{} }
func (m *Message) String() string { return proto.CompactTextString(m) }
func (*Message) ProtoMessage()    {}
func (*Message) Descriptor() ([]byte, []int) {
	return fileDescriptor_097b3f5db5cf5789, []int{0}
}

func (m *Message) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Message.Unmarshal(m, b)
}
func (m *Message) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Message.Marshal(b, m, deterministic)
}
func (m *Message) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Message.Merge(m, src)
}
func (m *Message) XXX_Size() int {
	return xxx_messageInfo_Message.Size(m)
}
func (m *Message) XXX_DiscardUnknown() {
	xxx_messageInfo_Message.DiscardUnknown(m)
}

var xxx_messageInfo_Message proto.InternalMessageInfo

func (m *Message) GetSay() string {
	if m != nil {
		return m.Say
	}
	return ""
}

type AddRequest struct {
	Mobile               string   `protobuf:"bytes,1,opt,name=Mobile,proto3" json:"Mobile,omitempty"`
	Data                 []byte   `protobuf:"bytes,2,opt,name=Data,proto3" json:"Data,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *AddRequest) Reset()         { *m = AddRequest{} }
func (m *AddRequest) String() string { return proto.CompactTextString(m) }
func (*AddRequest) ProtoMessage()    {}
func (*AddRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_097b3f5db5cf5789, []int{1}
}

func (m *AddRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_AddRequest.Unmarshal(m, b)
}
func (m *AddRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_AddRequest.Marshal(b, m, deterministic)
}
func (m *AddRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_AddRequest.Merge(m, src)
}
func (m *AddRequest) XXX_Size() int {
	return xxx_messageInfo_AddRequest.Size(m)
}
func (m *AddRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_AddRequest.DiscardUnknown(m)
}

var xxx_messageInfo_AddRequest proto.InternalMessageInfo

func (m *AddRequest) GetMobile() string {
	if m != nil {
		return m.Mobile
	}
	return ""
}

func (m *AddRequest) GetData() []byte {
	if m != nil {
		return m.Data
	}
	return nil
}

type AddResponse struct {
	Code                 string   `protobuf:"bytes,1,opt,name=Code,proto3" json:"Code,omitempty"`
	Msg                  string   `protobuf:"bytes,2,opt,name=Msg,proto3" json:"Msg,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *AddResponse) Reset()         { *m = AddResponse{} }
func (m *AddResponse) String() string { return proto.CompactTextString(m) }
func (*AddResponse) ProtoMessage()    {}
func (*AddResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_097b3f5db5cf5789, []int{2}
}

func (m *AddResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_AddResponse.Unmarshal(m, b)
}
func (m *AddResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_AddResponse.Marshal(b, m, deterministic)
}
func (m *AddResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_AddResponse.Merge(m, src)
}
func (m *AddResponse) XXX_Size() int {
	return xxx_messageInfo_AddResponse.Size(m)
}
func (m *AddResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_AddResponse.DiscardUnknown(m)
}

var xxx_messageInfo_AddResponse proto.InternalMessageInfo

func (m *AddResponse) GetCode() string {
	if m != nil {
		return m.Code
	}
	return ""
}

func (m *AddResponse) GetMsg() string {
	if m != nil {
		return m.Msg
	}
	return ""
}

type GetHouseListRequest struct {
	Mobile               string   `protobuf:"bytes,1,opt,name=Mobile,proto3" json:"Mobile,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetHouseListRequest) Reset()         { *m = GetHouseListRequest{} }
func (m *GetHouseListRequest) String() string { return proto.CompactTextString(m) }
func (*GetHouseListRequest) ProtoMessage()    {}
func (*GetHouseListRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_097b3f5db5cf5789, []int{3}
}

func (m *GetHouseListRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetHouseListRequest.Unmarshal(m, b)
}
func (m *GetHouseListRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetHouseListRequest.Marshal(b, m, deterministic)
}
func (m *GetHouseListRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetHouseListRequest.Merge(m, src)
}
func (m *GetHouseListRequest) XXX_Size() int {
	return xxx_messageInfo_GetHouseListRequest.Size(m)
}
func (m *GetHouseListRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_GetHouseListRequest.DiscardUnknown(m)
}

var xxx_messageInfo_GetHouseListRequest proto.InternalMessageInfo

func (m *GetHouseListRequest) GetMobile() string {
	if m != nil {
		return m.Mobile
	}
	return ""
}

type GetHouseListResponse struct {
	Code                 string   `protobuf:"bytes,1,opt,name=Code,proto3" json:"Code,omitempty"`
	Msg                  string   `protobuf:"bytes,2,opt,name=Msg,proto3" json:"Msg,omitempty"`
	Data                 []byte   `protobuf:"bytes,3,opt,name=Data,proto3" json:"Data,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetHouseListResponse) Reset()         { *m = GetHouseListResponse{} }
func (m *GetHouseListResponse) String() string { return proto.CompactTextString(m) }
func (*GetHouseListResponse) ProtoMessage()    {}
func (*GetHouseListResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_097b3f5db5cf5789, []int{4}
}

func (m *GetHouseListResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetHouseListResponse.Unmarshal(m, b)
}
func (m *GetHouseListResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetHouseListResponse.Marshal(b, m, deterministic)
}
func (m *GetHouseListResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetHouseListResponse.Merge(m, src)
}
func (m *GetHouseListResponse) XXX_Size() int {
	return xxx_messageInfo_GetHouseListResponse.Size(m)
}
func (m *GetHouseListResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_GetHouseListResponse.DiscardUnknown(m)
}

var xxx_messageInfo_GetHouseListResponse proto.InternalMessageInfo

func (m *GetHouseListResponse) GetCode() string {
	if m != nil {
		return m.Code
	}
	return ""
}

func (m *GetHouseListResponse) GetMsg() string {
	if m != nil {
		return m.Msg
	}
	return ""
}

func (m *GetHouseListResponse) GetData() []byte {
	if m != nil {
		return m.Data
	}
	return nil
}

type GetHouseDescRequest struct {
	HouseId              string   `protobuf:"bytes,1,opt,name=HouseId,proto3" json:"HouseId,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetHouseDescRequest) Reset()         { *m = GetHouseDescRequest{} }
func (m *GetHouseDescRequest) String() string { return proto.CompactTextString(m) }
func (*GetHouseDescRequest) ProtoMessage()    {}
func (*GetHouseDescRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_097b3f5db5cf5789, []int{5}
}

func (m *GetHouseDescRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetHouseDescRequest.Unmarshal(m, b)
}
func (m *GetHouseDescRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetHouseDescRequest.Marshal(b, m, deterministic)
}
func (m *GetHouseDescRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetHouseDescRequest.Merge(m, src)
}
func (m *GetHouseDescRequest) XXX_Size() int {
	return xxx_messageInfo_GetHouseDescRequest.Size(m)
}
func (m *GetHouseDescRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_GetHouseDescRequest.DiscardUnknown(m)
}

var xxx_messageInfo_GetHouseDescRequest proto.InternalMessageInfo

func (m *GetHouseDescRequest) GetHouseId() string {
	if m != nil {
		return m.HouseId
	}
	return ""
}

type GetHouseDescResponse struct {
	Code                 string   `protobuf:"bytes,1,opt,name=Code,proto3" json:"Code,omitempty"`
	Msg                  string   `protobuf:"bytes,2,opt,name=Msg,proto3" json:"Msg,omitempty"`
	Data                 []byte   `protobuf:"bytes,3,opt,name=Data,proto3" json:"Data,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetHouseDescResponse) Reset()         { *m = GetHouseDescResponse{} }
func (m *GetHouseDescResponse) String() string { return proto.CompactTextString(m) }
func (*GetHouseDescResponse) ProtoMessage()    {}
func (*GetHouseDescResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_097b3f5db5cf5789, []int{6}
}

func (m *GetHouseDescResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetHouseDescResponse.Unmarshal(m, b)
}
func (m *GetHouseDescResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetHouseDescResponse.Marshal(b, m, deterministic)
}
func (m *GetHouseDescResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetHouseDescResponse.Merge(m, src)
}
func (m *GetHouseDescResponse) XXX_Size() int {
	return xxx_messageInfo_GetHouseDescResponse.Size(m)
}
func (m *GetHouseDescResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_GetHouseDescResponse.DiscardUnknown(m)
}

var xxx_messageInfo_GetHouseDescResponse proto.InternalMessageInfo

func (m *GetHouseDescResponse) GetCode() string {
	if m != nil {
		return m.Code
	}
	return ""
}

func (m *GetHouseDescResponse) GetMsg() string {
	if m != nil {
		return m.Msg
	}
	return ""
}

func (m *GetHouseDescResponse) GetData() []byte {
	if m != nil {
		return m.Data
	}
	return nil
}

type UploadImageRequest struct {
	Mobile               string   `protobuf:"bytes,1,opt,name=Mobile,proto3" json:"Mobile,omitempty"`
	HouseId              string   `protobuf:"bytes,2,opt,name=HouseId,proto3" json:"HouseId,omitempty"`
	Data                 []byte   `protobuf:"bytes,3,opt,name=Data,proto3" json:"Data,omitempty"`
	FileName             string   `protobuf:"bytes,4,opt,name=FileName,proto3" json:"FileName,omitempty"`
	FileSize             int64    `protobuf:"varint,5,opt,name=FileSize,proto3" json:"FileSize,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *UploadImageRequest) Reset()         { *m = UploadImageRequest{} }
func (m *UploadImageRequest) String() string { return proto.CompactTextString(m) }
func (*UploadImageRequest) ProtoMessage()    {}
func (*UploadImageRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_097b3f5db5cf5789, []int{7}
}

func (m *UploadImageRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_UploadImageRequest.Unmarshal(m, b)
}
func (m *UploadImageRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_UploadImageRequest.Marshal(b, m, deterministic)
}
func (m *UploadImageRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_UploadImageRequest.Merge(m, src)
}
func (m *UploadImageRequest) XXX_Size() int {
	return xxx_messageInfo_UploadImageRequest.Size(m)
}
func (m *UploadImageRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_UploadImageRequest.DiscardUnknown(m)
}

var xxx_messageInfo_UploadImageRequest proto.InternalMessageInfo

func (m *UploadImageRequest) GetMobile() string {
	if m != nil {
		return m.Mobile
	}
	return ""
}

func (m *UploadImageRequest) GetHouseId() string {
	if m != nil {
		return m.HouseId
	}
	return ""
}

func (m *UploadImageRequest) GetData() []byte {
	if m != nil {
		return m.Data
	}
	return nil
}

func (m *UploadImageRequest) GetFileName() string {
	if m != nil {
		return m.FileName
	}
	return ""
}

func (m *UploadImageRequest) GetFileSize() int64 {
	if m != nil {
		return m.FileSize
	}
	return 0
}

type UploadImageResponse struct {
	Code                 string   `protobuf:"bytes,1,opt,name=Code,proto3" json:"Code,omitempty"`
	Msg                  string   `protobuf:"bytes,2,opt,name=Msg,proto3" json:"Msg,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *UploadImageResponse) Reset()         { *m = UploadImageResponse{} }
func (m *UploadImageResponse) String() string { return proto.CompactTextString(m) }
func (*UploadImageResponse) ProtoMessage()    {}
func (*UploadImageResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_097b3f5db5cf5789, []int{8}
}

func (m *UploadImageResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_UploadImageResponse.Unmarshal(m, b)
}
func (m *UploadImageResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_UploadImageResponse.Marshal(b, m, deterministic)
}
func (m *UploadImageResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_UploadImageResponse.Merge(m, src)
}
func (m *UploadImageResponse) XXX_Size() int {
	return xxx_messageInfo_UploadImageResponse.Size(m)
}
func (m *UploadImageResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_UploadImageResponse.DiscardUnknown(m)
}

var xxx_messageInfo_UploadImageResponse proto.InternalMessageInfo

func (m *UploadImageResponse) GetCode() string {
	if m != nil {
		return m.Code
	}
	return ""
}

func (m *UploadImageResponse) GetMsg() string {
	if m != nil {
		return m.Msg
	}
	return ""
}

type GetIndexListRequest struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetIndexListRequest) Reset()         { *m = GetIndexListRequest{} }
func (m *GetIndexListRequest) String() string { return proto.CompactTextString(m) }
func (*GetIndexListRequest) ProtoMessage()    {}
func (*GetIndexListRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_097b3f5db5cf5789, []int{9}
}

func (m *GetIndexListRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetIndexListRequest.Unmarshal(m, b)
}
func (m *GetIndexListRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetIndexListRequest.Marshal(b, m, deterministic)
}
func (m *GetIndexListRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetIndexListRequest.Merge(m, src)
}
func (m *GetIndexListRequest) XXX_Size() int {
	return xxx_messageInfo_GetIndexListRequest.Size(m)
}
func (m *GetIndexListRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_GetIndexListRequest.DiscardUnknown(m)
}

var xxx_messageInfo_GetIndexListRequest proto.InternalMessageInfo

type GetIndexListResponse struct {
	Code                 string   `protobuf:"bytes,1,opt,name=Code,proto3" json:"Code,omitempty"`
	Msg                  string   `protobuf:"bytes,2,opt,name=Msg,proto3" json:"Msg,omitempty"`
	Data                 []byte   `protobuf:"bytes,3,opt,name=Data,proto3" json:"Data,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetIndexListResponse) Reset()         { *m = GetIndexListResponse{} }
func (m *GetIndexListResponse) String() string { return proto.CompactTextString(m) }
func (*GetIndexListResponse) ProtoMessage()    {}
func (*GetIndexListResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_097b3f5db5cf5789, []int{10}
}

func (m *GetIndexListResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetIndexListResponse.Unmarshal(m, b)
}
func (m *GetIndexListResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetIndexListResponse.Marshal(b, m, deterministic)
}
func (m *GetIndexListResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetIndexListResponse.Merge(m, src)
}
func (m *GetIndexListResponse) XXX_Size() int {
	return xxx_messageInfo_GetIndexListResponse.Size(m)
}
func (m *GetIndexListResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_GetIndexListResponse.DiscardUnknown(m)
}

var xxx_messageInfo_GetIndexListResponse proto.InternalMessageInfo

func (m *GetIndexListResponse) GetCode() string {
	if m != nil {
		return m.Code
	}
	return ""
}

func (m *GetIndexListResponse) GetMsg() string {
	if m != nil {
		return m.Msg
	}
	return ""
}

func (m *GetIndexListResponse) GetData() []byte {
	if m != nil {
		return m.Data
	}
	return nil
}

func init() {
	proto.RegisterType((*Message)(nil), "go.micro.srv.house.Message")
	proto.RegisterType((*AddRequest)(nil), "go.micro.srv.house.AddRequest")
	proto.RegisterType((*AddResponse)(nil), "go.micro.srv.house.AddResponse")
	proto.RegisterType((*GetHouseListRequest)(nil), "go.micro.srv.house.GetHouseListRequest")
	proto.RegisterType((*GetHouseListResponse)(nil), "go.micro.srv.house.GetHouseListResponse")
	proto.RegisterType((*GetHouseDescRequest)(nil), "go.micro.srv.house.GetHouseDescRequest")
	proto.RegisterType((*GetHouseDescResponse)(nil), "go.micro.srv.house.GetHouseDescResponse")
	proto.RegisterType((*UploadImageRequest)(nil), "go.micro.srv.house.UploadImageRequest")
	proto.RegisterType((*UploadImageResponse)(nil), "go.micro.srv.house.UploadImageResponse")
	proto.RegisterType((*GetIndexListRequest)(nil), "go.micro.srv.house.GetIndexListRequest")
	proto.RegisterType((*GetIndexListResponse)(nil), "go.micro.srv.house.GetIndexListResponse")
}

func init() { proto.RegisterFile("proto/example/example.proto", fileDescriptor_097b3f5db5cf5789) }

var fileDescriptor_097b3f5db5cf5789 = []byte{
	// 407 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xa4, 0x54, 0xc1, 0x6e, 0xda, 0x40,
	0x10, 0xc5, 0x98, 0x42, 0x19, 0x38, 0x54, 0x4b, 0x5b, 0x59, 0x46, 0x6a, 0xd1, 0x1e, 0x8a, 0x2f,
	0x35, 0x52, 0xb9, 0x54, 0xea, 0x09, 0x95, 0x24, 0x20, 0x85, 0x28, 0x72, 0x94, 0x7b, 0x16, 0x76,
	0xe5, 0x58, 0xb2, 0x59, 0x87, 0x35, 0x11, 0xc9, 0x67, 0xe4, 0x1b, 0xf3, 0x21, 0x91, 0x17, 0xdb,
	0x2c, 0x60, 0xb0, 0x10, 0x27, 0xcf, 0xec, 0xce, 0xdb, 0xf7, 0x66, 0xe6, 0xc9, 0xd0, 0x0e, 0x17,
	0x3c, 0xe2, 0x3d, 0xb6, 0x22, 0x41, 0xe8, 0xb3, 0xf4, 0x6b, 0xcb, 0x53, 0x84, 0x5c, 0x6e, 0x07,
	0xde, 0x6c, 0xc1, 0x6d, 0xb1, 0x78, 0xb6, 0x1f, 0xf9, 0x52, 0x30, 0xdc, 0x86, 0xda, 0x84, 0x09,
	0x41, 0x5c, 0x86, 0xbe, 0x80, 0x2e, 0xc8, 0x8b, 0xa1, 0x75, 0x34, 0xab, 0xee, 0xc4, 0x21, 0xfe,
	0x0b, 0x30, 0xa0, 0xd4, 0x61, 0x4f, 0x4b, 0x26, 0x22, 0xf4, 0x1d, 0xaa, 0x13, 0x3e, 0xf5, 0x7c,
	0x96, 0x94, 0x24, 0x19, 0x42, 0x50, 0x19, 0x92, 0x88, 0x18, 0xe5, 0x8e, 0x66, 0x35, 0x1d, 0x19,
	0xe3, 0x3e, 0x34, 0x24, 0x52, 0x84, 0x7c, 0x2e, 0x64, 0xc9, 0x7f, 0x4e, 0x53, 0xa0, 0x8c, 0x63,
	0xba, 0x89, 0x70, 0x25, 0xaa, 0xee, 0xc4, 0x21, 0xfe, 0x0d, 0xad, 0x2b, 0x16, 0x8d, 0x62, 0x5d,
	0xd7, 0x9e, 0x88, 0x0a, 0x78, 0xf1, 0x2d, 0x7c, 0xdd, 0x2e, 0x3f, 0x85, 0x2c, 0x53, 0xad, 0x2b,
	0xaa, 0x7b, 0x1b, 0x01, 0x43, 0x26, 0x66, 0xa9, 0x00, 0x03, 0x6a, 0xf2, 0x6c, 0x4c, 0x93, 0x37,
	0xd3, 0x54, 0x95, 0xb0, 0x06, 0x9c, 0x2d, 0xe1, 0x4d, 0x03, 0x74, 0x1f, 0xfa, 0x9c, 0xd0, 0x71,
	0x40, 0x5c, 0x56, 0x34, 0x7b, 0x45, 0x5a, 0x79, 0x4b, 0x5a, 0xde, 0xe3, 0xc8, 0x84, 0xcf, 0x97,
	0x9e, 0xcf, 0x6e, 0x48, 0xc0, 0x8c, 0x8a, 0x2c, 0xcf, 0xf2, 0xf4, 0xee, 0xce, 0x7b, 0x65, 0xc6,
	0xa7, 0x8e, 0x66, 0xe9, 0x4e, 0x96, 0xe3, 0x7f, 0xd0, 0xda, 0xd2, 0x74, 0xd2, 0x56, 0xbf, 0xc9,
	0xa1, 0x8e, 0xe7, 0x94, 0xad, 0x94, 0xad, 0x26, 0xa3, 0x53, 0x8e, 0xcf, 0x1d, 0xdd, 0x9f, 0x77,
	0x1d, 0x6a, 0x17, 0x6b, 0xc3, 0xa3, 0x11, 0xe8, 0x03, 0x4a, 0xd1, 0x0f, 0x7b, 0xdf, 0xf2, 0xf6,
	0xc6, 0xd2, 0xe6, 0xcf, 0x83, 0xf7, 0x6b, 0x35, 0xb8, 0x84, 0x66, 0xd0, 0x54, 0x5d, 0x86, 0xba,
	0x79, 0x90, 0x1c, 0xdb, 0x9a, 0x56, 0x71, 0x61, 0x1e, 0x49, 0xec, 0xa3, 0xe3, 0x24, 0x8a, 0x35,
	0x8f, 0x93, 0xa8, 0x96, 0xc4, 0x25, 0xf4, 0x00, 0x0d, 0x65, 0x8b, 0xe8, 0x57, 0x1e, 0x74, 0xdf,
	0x7a, 0x66, 0xb7, 0xb0, 0x6e, 0xa7, 0x8d, 0x6c, 0xa7, 0x07, 0xdb, 0xd8, 0x35, 0xc3, 0xc1, 0x36,
	0xf6, 0xec, 0x81, 0x4b, 0xd3, 0xaa, 0xfc, 0x99, 0xf5, 0x3f, 0x02, 0x00, 0x00, 0xff, 0xff, 0x84,
	0xed, 0x01, 0x70, 0xeb, 0x04, 0x00, 0x00,
}
