// Code generated by protoc-gen-go. DO NOT EDIT.
// source: proto/example/example.proto

package go_micro_srv_house

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type Message struct {
	Say                  string   `protobuf:"bytes,1,opt,name=say,proto3" json:"say,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Message) Reset()         { *m = Message{} }
func (m *Message) String() string { return proto.CompactTextString(m) }
func (*Message) ProtoMessage()    {}
func (*Message) Descriptor() ([]byte, []int) {
	return fileDescriptor_097b3f5db5cf5789, []int{0}
}

func (m *Message) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Message.Unmarshal(m, b)
}
func (m *Message) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Message.Marshal(b, m, deterministic)
}
func (m *Message) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Message.Merge(m, src)
}
func (m *Message) XXX_Size() int {
	return xxx_messageInfo_Message.Size(m)
}
func (m *Message) XXX_DiscardUnknown() {
	xxx_messageInfo_Message.DiscardUnknown(m)
}

var xxx_messageInfo_Message proto.InternalMessageInfo

func (m *Message) GetSay() string {
	if m != nil {
		return m.Say
	}
	return ""
}

type AddRequest struct {
	Data                 []byte   `protobuf:"bytes,1,opt,name=Data,proto3" json:"Data,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *AddRequest) Reset()         { *m = AddRequest{} }
func (m *AddRequest) String() string { return proto.CompactTextString(m) }
func (*AddRequest) ProtoMessage()    {}
func (*AddRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_097b3f5db5cf5789, []int{1}
}

func (m *AddRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_AddRequest.Unmarshal(m, b)
}
func (m *AddRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_AddRequest.Marshal(b, m, deterministic)
}
func (m *AddRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_AddRequest.Merge(m, src)
}
func (m *AddRequest) XXX_Size() int {
	return xxx_messageInfo_AddRequest.Size(m)
}
func (m *AddRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_AddRequest.DiscardUnknown(m)
}

var xxx_messageInfo_AddRequest proto.InternalMessageInfo

func (m *AddRequest) GetData() []byte {
	if m != nil {
		return m.Data
	}
	return nil
}

type AddResponse struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *AddResponse) Reset()         { *m = AddResponse{} }
func (m *AddResponse) String() string { return proto.CompactTextString(m) }
func (*AddResponse) ProtoMessage()    {}
func (*AddResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_097b3f5db5cf5789, []int{2}
}

func (m *AddResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_AddResponse.Unmarshal(m, b)
}
func (m *AddResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_AddResponse.Marshal(b, m, deterministic)
}
func (m *AddResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_AddResponse.Merge(m, src)
}
func (m *AddResponse) XXX_Size() int {
	return xxx_messageInfo_AddResponse.Size(m)
}
func (m *AddResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_AddResponse.DiscardUnknown(m)
}

var xxx_messageInfo_AddResponse proto.InternalMessageInfo

type GetLandlordListRequest struct {
	Mobile               string   `protobuf:"bytes,1,opt,name=Mobile,proto3" json:"Mobile,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetLandlordListRequest) Reset()         { *m = GetLandlordListRequest{} }
func (m *GetLandlordListRequest) String() string { return proto.CompactTextString(m) }
func (*GetLandlordListRequest) ProtoMessage()    {}
func (*GetLandlordListRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_097b3f5db5cf5789, []int{3}
}

func (m *GetLandlordListRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetLandlordListRequest.Unmarshal(m, b)
}
func (m *GetLandlordListRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetLandlordListRequest.Marshal(b, m, deterministic)
}
func (m *GetLandlordListRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetLandlordListRequest.Merge(m, src)
}
func (m *GetLandlordListRequest) XXX_Size() int {
	return xxx_messageInfo_GetLandlordListRequest.Size(m)
}
func (m *GetLandlordListRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_GetLandlordListRequest.DiscardUnknown(m)
}

var xxx_messageInfo_GetLandlordListRequest proto.InternalMessageInfo

func (m *GetLandlordListRequest) GetMobile() string {
	if m != nil {
		return m.Mobile
	}
	return ""
}

type GetLandlordListResponse struct {
	Data                 []byte   `protobuf:"bytes,1,opt,name=Data,proto3" json:"Data,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetLandlordListResponse) Reset()         { *m = GetLandlordListResponse{} }
func (m *GetLandlordListResponse) String() string { return proto.CompactTextString(m) }
func (*GetLandlordListResponse) ProtoMessage()    {}
func (*GetLandlordListResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_097b3f5db5cf5789, []int{4}
}

func (m *GetLandlordListResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetLandlordListResponse.Unmarshal(m, b)
}
func (m *GetLandlordListResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetLandlordListResponse.Marshal(b, m, deterministic)
}
func (m *GetLandlordListResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetLandlordListResponse.Merge(m, src)
}
func (m *GetLandlordListResponse) XXX_Size() int {
	return xxx_messageInfo_GetLandlordListResponse.Size(m)
}
func (m *GetLandlordListResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_GetLandlordListResponse.DiscardUnknown(m)
}

var xxx_messageInfo_GetLandlordListResponse proto.InternalMessageInfo

func (m *GetLandlordListResponse) GetData() []byte {
	if m != nil {
		return m.Data
	}
	return nil
}

type UploadImageRequest struct {
	Mobile               string   `protobuf:"bytes,1,opt,name=Mobile,proto3" json:"Mobile,omitempty"`
	HouseId              string   `protobuf:"bytes,2,opt,name=HouseId,proto3" json:"HouseId,omitempty"`
	Data                 []byte   `protobuf:"bytes,3,opt,name=Data,proto3" json:"Data,omitempty"`
	FileName             string   `protobuf:"bytes,4,opt,name=FileName,proto3" json:"FileName,omitempty"`
	FileSize             int64    `protobuf:"varint,5,opt,name=FileSize,proto3" json:"FileSize,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *UploadImageRequest) Reset()         { *m = UploadImageRequest{} }
func (m *UploadImageRequest) String() string { return proto.CompactTextString(m) }
func (*UploadImageRequest) ProtoMessage()    {}
func (*UploadImageRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_097b3f5db5cf5789, []int{5}
}

func (m *UploadImageRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_UploadImageRequest.Unmarshal(m, b)
}
func (m *UploadImageRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_UploadImageRequest.Marshal(b, m, deterministic)
}
func (m *UploadImageRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_UploadImageRequest.Merge(m, src)
}
func (m *UploadImageRequest) XXX_Size() int {
	return xxx_messageInfo_UploadImageRequest.Size(m)
}
func (m *UploadImageRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_UploadImageRequest.DiscardUnknown(m)
}

var xxx_messageInfo_UploadImageRequest proto.InternalMessageInfo

func (m *UploadImageRequest) GetMobile() string {
	if m != nil {
		return m.Mobile
	}
	return ""
}

func (m *UploadImageRequest) GetHouseId() string {
	if m != nil {
		return m.HouseId
	}
	return ""
}

func (m *UploadImageRequest) GetData() []byte {
	if m != nil {
		return m.Data
	}
	return nil
}

func (m *UploadImageRequest) GetFileName() string {
	if m != nil {
		return m.FileName
	}
	return ""
}

func (m *UploadImageRequest) GetFileSize() int64 {
	if m != nil {
		return m.FileSize
	}
	return 0
}

type UploadImageResponse struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *UploadImageResponse) Reset()         { *m = UploadImageResponse{} }
func (m *UploadImageResponse) String() string { return proto.CompactTextString(m) }
func (*UploadImageResponse) ProtoMessage()    {}
func (*UploadImageResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_097b3f5db5cf5789, []int{6}
}

func (m *UploadImageResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_UploadImageResponse.Unmarshal(m, b)
}
func (m *UploadImageResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_UploadImageResponse.Marshal(b, m, deterministic)
}
func (m *UploadImageResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_UploadImageResponse.Merge(m, src)
}
func (m *UploadImageResponse) XXX_Size() int {
	return xxx_messageInfo_UploadImageResponse.Size(m)
}
func (m *UploadImageResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_UploadImageResponse.DiscardUnknown(m)
}

var xxx_messageInfo_UploadImageResponse proto.InternalMessageInfo

type GetDescRequest struct {
	HouseId              string   `protobuf:"bytes,1,opt,name=HouseId,proto3" json:"HouseId,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetDescRequest) Reset()         { *m = GetDescRequest{} }
func (m *GetDescRequest) String() string { return proto.CompactTextString(m) }
func (*GetDescRequest) ProtoMessage()    {}
func (*GetDescRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_097b3f5db5cf5789, []int{7}
}

func (m *GetDescRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetDescRequest.Unmarshal(m, b)
}
func (m *GetDescRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetDescRequest.Marshal(b, m, deterministic)
}
func (m *GetDescRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetDescRequest.Merge(m, src)
}
func (m *GetDescRequest) XXX_Size() int {
	return xxx_messageInfo_GetDescRequest.Size(m)
}
func (m *GetDescRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_GetDescRequest.DiscardUnknown(m)
}

var xxx_messageInfo_GetDescRequest proto.InternalMessageInfo

func (m *GetDescRequest) GetHouseId() string {
	if m != nil {
		return m.HouseId
	}
	return ""
}

type GetDescResponse struct {
	Data                 []byte   `protobuf:"bytes,1,opt,name=Data,proto3" json:"Data,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetDescResponse) Reset()         { *m = GetDescResponse{} }
func (m *GetDescResponse) String() string { return proto.CompactTextString(m) }
func (*GetDescResponse) ProtoMessage()    {}
func (*GetDescResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_097b3f5db5cf5789, []int{8}
}

func (m *GetDescResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetDescResponse.Unmarshal(m, b)
}
func (m *GetDescResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetDescResponse.Marshal(b, m, deterministic)
}
func (m *GetDescResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetDescResponse.Merge(m, src)
}
func (m *GetDescResponse) XXX_Size() int {
	return xxx_messageInfo_GetDescResponse.Size(m)
}
func (m *GetDescResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_GetDescResponse.DiscardUnknown(m)
}

var xxx_messageInfo_GetDescResponse proto.InternalMessageInfo

func (m *GetDescResponse) GetData() []byte {
	if m != nil {
		return m.Data
	}
	return nil
}

type SearchRequest struct {
	AreaId               string   `protobuf:"bytes,1,opt,name=AreaId,proto3" json:"AreaId,omitempty"`
	Start                string   `protobuf:"bytes,2,opt,name=Start,proto3" json:"Start,omitempty"`
	End                  string   `protobuf:"bytes,3,opt,name=End,proto3" json:"End,omitempty"`
	Page                 string   `protobuf:"bytes,4,opt,name=Page,proto3" json:"Page,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *SearchRequest) Reset()         { *m = SearchRequest{} }
func (m *SearchRequest) String() string { return proto.CompactTextString(m) }
func (*SearchRequest) ProtoMessage()    {}
func (*SearchRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_097b3f5db5cf5789, []int{9}
}

func (m *SearchRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SearchRequest.Unmarshal(m, b)
}
func (m *SearchRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SearchRequest.Marshal(b, m, deterministic)
}
func (m *SearchRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SearchRequest.Merge(m, src)
}
func (m *SearchRequest) XXX_Size() int {
	return xxx_messageInfo_SearchRequest.Size(m)
}
func (m *SearchRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_SearchRequest.DiscardUnknown(m)
}

var xxx_messageInfo_SearchRequest proto.InternalMessageInfo

func (m *SearchRequest) GetAreaId() string {
	if m != nil {
		return m.AreaId
	}
	return ""
}

func (m *SearchRequest) GetStart() string {
	if m != nil {
		return m.Start
	}
	return ""
}

func (m *SearchRequest) GetEnd() string {
	if m != nil {
		return m.End
	}
	return ""
}

func (m *SearchRequest) GetPage() string {
	if m != nil {
		return m.Page
	}
	return ""
}

type SearchResponse struct {
	Data                 []byte   `protobuf:"bytes,1,opt,name=Data,proto3" json:"Data,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *SearchResponse) Reset()         { *m = SearchResponse{} }
func (m *SearchResponse) String() string { return proto.CompactTextString(m) }
func (*SearchResponse) ProtoMessage()    {}
func (*SearchResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_097b3f5db5cf5789, []int{10}
}

func (m *SearchResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SearchResponse.Unmarshal(m, b)
}
func (m *SearchResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SearchResponse.Marshal(b, m, deterministic)
}
func (m *SearchResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SearchResponse.Merge(m, src)
}
func (m *SearchResponse) XXX_Size() int {
	return xxx_messageInfo_SearchResponse.Size(m)
}
func (m *SearchResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_SearchResponse.DiscardUnknown(m)
}

var xxx_messageInfo_SearchResponse proto.InternalMessageInfo

func (m *SearchResponse) GetData() []byte {
	if m != nil {
		return m.Data
	}
	return nil
}

func init() {
	proto.RegisterType((*Message)(nil), "go.micro.srv.house.Message")
	proto.RegisterType((*AddRequest)(nil), "go.micro.srv.house.AddRequest")
	proto.RegisterType((*AddResponse)(nil), "go.micro.srv.house.AddResponse")
	proto.RegisterType((*GetLandlordListRequest)(nil), "go.micro.srv.house.GetLandlordListRequest")
	proto.RegisterType((*GetLandlordListResponse)(nil), "go.micro.srv.house.GetLandlordListResponse")
	proto.RegisterType((*UploadImageRequest)(nil), "go.micro.srv.house.UploadImageRequest")
	proto.RegisterType((*UploadImageResponse)(nil), "go.micro.srv.house.UploadImageResponse")
	proto.RegisterType((*GetDescRequest)(nil), "go.micro.srv.house.GetDescRequest")
	proto.RegisterType((*GetDescResponse)(nil), "go.micro.srv.house.GetDescResponse")
	proto.RegisterType((*SearchRequest)(nil), "go.micro.srv.house.SearchRequest")
	proto.RegisterType((*SearchResponse)(nil), "go.micro.srv.house.SearchResponse")
}

func init() { proto.RegisterFile("proto/example/example.proto", fileDescriptor_097b3f5db5cf5789) }

var fileDescriptor_097b3f5db5cf5789 = []byte{
	// 434 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x8c, 0x54, 0xff, 0x4e, 0xd4, 0x40,
	0x10, 0xb6, 0x16, 0xae, 0x32, 0x08, 0x9a, 0x51, 0xb1, 0x29, 0x89, 0x9e, 0xeb, 0x2f, 0x82, 0xb1,
	0x1a, 0x7d, 0x82, 0x4b, 0x40, 0x20, 0x01, 0xa3, 0x3d, 0xfd, 0xdf, 0xa5, 0x3b, 0x29, 0x4d, 0xda,
	0xdb, 0xda, 0x5d, 0x8c, 0xfa, 0x18, 0x3e, 0x97, 0x0f, 0x65, 0xba, 0xed, 0x2e, 0xbd, 0x5c, 0xef,
	0xf0, 0xaf, 0x9b, 0xb9, 0xfd, 0xe6, 0x9b, 0xf9, 0x66, 0xbe, 0x14, 0x76, 0xab, 0x5a, 0x6a, 0xf9,
	0x86, 0x7e, 0xf2, 0xb2, 0x2a, 0xc8, 0xfe, 0xc6, 0xe6, 0x5f, 0xc4, 0x4c, 0xc6, 0x65, 0x9e, 0xd6,
	0x32, 0x56, 0xf5, 0x8f, 0xf8, 0x42, 0x5e, 0x2a, 0x62, 0xbb, 0x10, 0x9c, 0x91, 0x52, 0x3c, 0x23,
	0xbc, 0x0b, 0xbe, 0xe2, 0xbf, 0x42, 0x6f, 0xec, 0xed, 0x6d, 0x24, 0x4d, 0xc8, 0xc6, 0x00, 0x13,
	0x21, 0x12, 0xfa, 0x7e, 0x49, 0x4a, 0x23, 0xc2, 0xda, 0x01, 0xd7, 0xdc, 0x00, 0x6e, 0x27, 0x26,
	0x66, 0x5b, 0xb0, 0x69, 0x10, 0xaa, 0x92, 0x33, 0x45, 0xec, 0x2d, 0xec, 0x1c, 0x91, 0x3e, 0xe5,
	0x33, 0x51, 0xc8, 0x5a, 0x9c, 0xe6, 0x4a, 0xdb, 0xe2, 0x1d, 0x18, 0x9d, 0xc9, 0xf3, 0xbc, 0xa0,
	0x8e, 0xbf, 0xcb, 0xd8, 0x6b, 0x78, 0xb8, 0x50, 0xd1, 0x92, 0x0d, 0xf6, 0xfb, 0xe3, 0x01, 0x7e,
	0xad, 0x0a, 0xc9, 0xc5, 0x49, 0xc9, 0x33, 0xba, 0x86, 0x1d, 0x43, 0x08, 0x8e, 0x1b, 0x99, 0x27,
	0x22, 0xbc, 0x69, 0x1e, 0x6c, 0xea, 0xc8, 0xfd, 0x2b, 0x72, 0x8c, 0xe0, 0xd6, 0x87, 0xbc, 0xa0,
	0x8f, 0xbc, 0xa4, 0x70, 0xcd, 0xc0, 0x5d, 0x6e, 0xdf, 0xa6, 0xf9, 0x6f, 0x0a, 0xd7, 0xc7, 0xde,
	0x9e, 0x9f, 0xb8, 0x9c, 0x3d, 0x80, 0x7b, 0x73, 0x33, 0x75, 0xcb, 0xd8, 0x87, 0xed, 0x23, 0xd2,
	0x07, 0xa4, 0x52, 0x3b, 0x66, 0x6f, 0x1c, 0x6f, 0x6e, 0x1c, 0xf6, 0x1c, 0xee, 0x38, 0xec, 0x0a,
	0xf9, 0x29, 0x6c, 0x4d, 0x89, 0xd7, 0xe9, 0x45, 0x4f, 0xf8, 0xa4, 0x26, 0xee, 0x08, 0xbb, 0x0c,
	0xef, 0xc3, 0xfa, 0x54, 0xf3, 0x5a, 0x77, 0xb2, 0xdb, 0xa4, 0xb9, 0xf0, 0xe1, 0x4c, 0x18, 0xcd,
	0x1b, 0x49, 0x13, 0x36, 0x4d, 0x3e, 0xf1, 0xcc, 0xca, 0x35, 0x31, 0x7b, 0x06, 0xdb, 0xb6, 0xc9,
	0xf2, 0x51, 0xde, 0xfd, 0xf5, 0x21, 0x38, 0x6c, 0xed, 0x85, 0xc7, 0xe0, 0x4f, 0x84, 0xc0, 0x47,
	0xf1, 0xa2, 0xc1, 0xe2, 0x2b, 0x03, 0x45, 0x8f, 0x97, 0xbe, 0x77, 0x1b, 0xbb, 0x81, 0x85, 0xd9,
	0x43, 0xdf, 0x0e, 0xb8, 0x3f, 0x54, 0x35, 0xec, 0xb2, 0xe8, 0xd5, 0x7f, 0x61, 0x5d, 0xb7, 0x6f,
	0xb0, 0xd9, 0x3b, 0x1c, 0xbe, 0x18, 0xaa, 0x5e, 0x74, 0x5b, 0xf4, 0xf2, 0x5a, 0x9c, 0xeb, 0xf0,
	0x05, 0x82, 0xee, 0xae, 0xc8, 0x96, 0xcc, 0xd6, 0x33, 0x48, 0xf4, 0x74, 0x25, 0xc6, 0xb1, 0x7e,
	0x86, 0x51, 0x7b, 0x21, 0x7c, 0x32, 0x54, 0x30, 0x67, 0x91, 0x88, 0xad, 0x82, 0x58, 0xca, 0xf3,
	0x91, 0xf9, 0x44, 0xbc, 0xff, 0x17, 0x00, 0x00, 0xff, 0xff, 0x57, 0xba, 0x89, 0xf5, 0x41, 0x04,
	0x00, 0x00,
}
