// Code generated by protoc-gen-go. DO NOT EDIT.
// source: proto/example/example.proto

package go_micro_srv_area

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type Message struct {
	Say                  string   `protobuf:"bytes,1,opt,name=say,proto3" json:"say,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Message) Reset()         { *m = Message{} }
func (m *Message) String() string { return proto.CompactTextString(m) }
func (*Message) ProtoMessage()    {}
func (*Message) Descriptor() ([]byte, []int) {
	return fileDescriptor_097b3f5db5cf5789, []int{0}
}

func (m *Message) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Message.Unmarshal(m, b)
}
func (m *Message) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Message.Marshal(b, m, deterministic)
}
func (m *Message) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Message.Merge(m, src)
}
func (m *Message) XXX_Size() int {
	return xxx_messageInfo_Message.Size(m)
}
func (m *Message) XXX_DiscardUnknown() {
	xxx_messageInfo_Message.DiscardUnknown(m)
}

var xxx_messageInfo_Message proto.InternalMessageInfo

func (m *Message) GetSay() string {
	if m != nil {
		return m.Say
	}
	return ""
}

type GetAreaListRequest struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetAreaListRequest) Reset()         { *m = GetAreaListRequest{} }
func (m *GetAreaListRequest) String() string { return proto.CompactTextString(m) }
func (*GetAreaListRequest) ProtoMessage()    {}
func (*GetAreaListRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_097b3f5db5cf5789, []int{1}
}

func (m *GetAreaListRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetAreaListRequest.Unmarshal(m, b)
}
func (m *GetAreaListRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetAreaListRequest.Marshal(b, m, deterministic)
}
func (m *GetAreaListRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetAreaListRequest.Merge(m, src)
}
func (m *GetAreaListRequest) XXX_Size() int {
	return xxx_messageInfo_GetAreaListRequest.Size(m)
}
func (m *GetAreaListRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_GetAreaListRequest.DiscardUnknown(m)
}

var xxx_messageInfo_GetAreaListRequest proto.InternalMessageInfo

type GetAreaListResponse struct {
	Data                 []byte   `protobuf:"bytes,1,opt,name=Data,proto3" json:"Data,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetAreaListResponse) Reset()         { *m = GetAreaListResponse{} }
func (m *GetAreaListResponse) String() string { return proto.CompactTextString(m) }
func (*GetAreaListResponse) ProtoMessage()    {}
func (*GetAreaListResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_097b3f5db5cf5789, []int{2}
}

func (m *GetAreaListResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetAreaListResponse.Unmarshal(m, b)
}
func (m *GetAreaListResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetAreaListResponse.Marshal(b, m, deterministic)
}
func (m *GetAreaListResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetAreaListResponse.Merge(m, src)
}
func (m *GetAreaListResponse) XXX_Size() int {
	return xxx_messageInfo_GetAreaListResponse.Size(m)
}
func (m *GetAreaListResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_GetAreaListResponse.DiscardUnknown(m)
}

var xxx_messageInfo_GetAreaListResponse proto.InternalMessageInfo

func (m *GetAreaListResponse) GetData() []byte {
	if m != nil {
		return m.Data
	}
	return nil
}

func init() {
	proto.RegisterType((*Message)(nil), "go.micro.srv.area.Message")
	proto.RegisterType((*GetAreaListRequest)(nil), "go.micro.srv.area.GetAreaListRequest")
	proto.RegisterType((*GetAreaListResponse)(nil), "go.micro.srv.area.GetAreaListResponse")
}

func init() { proto.RegisterFile("proto/example/example.proto", fileDescriptor_097b3f5db5cf5789) }

var fileDescriptor_097b3f5db5cf5789 = []byte{
	// 173 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xe2, 0x92, 0x2e, 0x28, 0xca, 0x2f,
	0xc9, 0xd7, 0x4f, 0xad, 0x48, 0xcc, 0x2d, 0xc8, 0x49, 0x85, 0xd1, 0x7a, 0x60, 0x51, 0x21, 0xc1,
	0xf4, 0x7c, 0xbd, 0xdc, 0xcc, 0xe4, 0xa2, 0x7c, 0xbd, 0xe2, 0xa2, 0x32, 0xbd, 0xc4, 0xa2, 0xd4,
	0x44, 0x25, 0x69, 0x2e, 0x76, 0xdf, 0xd4, 0xe2, 0xe2, 0xc4, 0xf4, 0x54, 0x21, 0x01, 0x2e, 0xe6,
	0xe2, 0xc4, 0x4a, 0x09, 0x46, 0x05, 0x46, 0x0d, 0xce, 0x20, 0x10, 0x53, 0x49, 0x84, 0x4b, 0xc8,
	0x3d, 0xb5, 0xc4, 0xb1, 0x28, 0x35, 0xd1, 0x27, 0xb3, 0xb8, 0x24, 0x28, 0xb5, 0xb0, 0x34, 0xb5,
	0xb8, 0x44, 0x49, 0x93, 0x4b, 0x18, 0x45, 0xb4, 0xb8, 0x20, 0x3f, 0xaf, 0x38, 0x55, 0x48, 0x88,
	0x8b, 0xc5, 0x25, 0xb1, 0x24, 0x11, 0xac, 0x9f, 0x27, 0x08, 0xcc, 0x36, 0xca, 0xe4, 0x62, 0x77,
	0x85, 0xb8, 0x40, 0x28, 0x8e, 0x8b, 0x1b, 0x49, 0x97, 0x90, 0xaa, 0x1e, 0x86, 0x5b, 0xf4, 0x30,
	0xed, 0x92, 0x52, 0x23, 0xa4, 0x0c, 0x62, 0xb9, 0x12, 0x43, 0x12, 0x1b, 0xd8, 0x8b, 0xc6, 0x80,
	0x00, 0x00, 0x00, 0xff, 0xff, 0xb3, 0x9f, 0x70, 0x6d, 0x01, 0x01, 0x00, 0x00,
}
